### ISSUE TITLE
Please delete posted in wrong Bucket

### ISSUE THREAD

**Issue by Rahulhasmail** [bitfocus/companion#1015]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
A clear and concise description of what the feature does

**Is this platform-dependent (windows, mac, ..)?**
Both Windows & Mac

**If documentation is required to implement, do you know where to find it?**
https://www.novastar.tech/wp-content/uploads/2019/11/J6-Seamless-Switcher-User-Manual-V2.2.0.pdf?x83108

**Usecases**
when Using Live Projection, Background graphics are fed via Computer, and need of scene switch trigger arises considering different layout in each scene

**Comment by McHauge** [comment]
???

**Comment by Rahulhasmail** [comment]
Dear Andreas,
Greetings!

Can I request Bitfocus/Companion Team to create control codes for Novastar
J6_Switching presets


Thanks & Regards
Rahul Chawda

**Comment by McHauge** [comment]
@Rahulhasmail yes, I typed that comment because on my screen it was just an empty request. but please re-upload the request the correct place, this is for the Companion Core. Go to the link below and post a module request over there: [Module request](https://github.com/bitfocus/companion-module-requests/issues/new)
