### ISSUE TITLE
Module Request: CasparCG

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#105]
**Describe the feature**
Control and feedback from CasparCG

**Is this platform dependent (windows, mac, ..)?**

Server is Windows

**If documentation is required to implement, do you know where to find it?**
Control (via AMCP) 

https://github.com/CasparCG/help/wiki/AMCP-Protocol

Feedback (via OSC)

https://github.com/CasparCG/help/wiki/OSC-Protocol

**Usecases**
Control and feedback from CasparCG

**Comment by haakonnessjoen** [comment]
So, for example. You would have to Schedule a LOADBG action that has channel and optional layout options, as well as string for specifying the file to load, and then a PLAY action, that also needs the same parameters?

Should it have dropdowns for all possible options, like transitions etc?

Or how would you like to control CasparCG? Since it doesn't really have an internal playlist, as far as I know?

**Comment by Keksstar** [comment]
Well all the stuff could be done with an TCP module. But due to the fact you don´t want to hand out an TCP module to the peoples and want to create modules: Yes, please add dropdowns for all possible options and the possbility to control multiple Caspar Servers from one button ;-)

Yes, Caspar Servers don´t have an internal playlist. The playlists happens in the Clients.

**Comment by silid** [comment]
Why was this issue closed?

**Comment by haakonnessjoen** [comment]
This is implemented in the latest build. But please test, I did not have a CasparCG machine available.
