### ISSUE TITLE
[BUG] Infinitton not showing up under surfaces

### ISSUE THREAD

**Issue by rikroukens** [bitfocus/companion#1070]
**Describe the bug**
Infinitton doesn't show up on surfaces tab. (running latest build: 2.0.0-efc21be-2272 also didn't show up when running 1.4)

I've noticed it does show up in companion under dbug:
`08. 12:33:09 device(D434315B1A0129): Infinitton detected`

Re-scanning the USBs doesn't change anything (I assume as it is already connected)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Companion Version: 2.0.0-efc21be-2272

**Comment by rikroukens** [comment]
When pressing the rescan button a few times, it looks like the Infinitton screen went black completely (like it is unplugged) this might indicate that companion is driving the screens? I decided to remove the usb and companion threw an error. [see screenshot here](https://imgur.com/uW202Up)

**Comment by gnomatron** [comment]
Hi!
The bug I'm experiencing with my infinitton has similar behaviour, it's showing up under debug and i get the same error messages, black screen etc.

**Comment by haakonnessjoen** [comment]
Could you give more information about companion version and operating system on yours too @gnomatron ?

**Comment by gnomatron** [comment]
sure, I left them in the bug request I opened because it looked like a similar but different issue but now I'm not so sure:

windows 8.1 laptop - my infinitton doesn't show up properly in the surfaces tab of the GUI.

Companion v1.4.0, backport-b402e70-1559

A blank line (sometimes) appears under the streamdeck emulator when the infinitton is connected. I also sometimes see the infinitton detected in the debug window, but not listed under surfaces.

I've tried with the smart editor both running and NOT running, neither helps.

The same companion software version on my macbook pro running 10.14.6 works just fine.

I feel like it may be an OS related issue, as the infinitton editor claims to be for win 10, so i might try an OS upgrade.

**Comment by rikroukens** [comment]
@gnomatron what you describe sounds like exactly the same issue as I'm having. @haakonnessjoen I'm on Windows 10 myself.

**Comment by gnomatron** [comment]
I've upgraded the computer to windows 10, the problem persists just the same.

**Comment by gnomatron** [comment]
Tried installing companion v2.2.2 (2.0.0-720bb55-2276), infinitton still does not connect; no longer see the infinitton detected in debug, but I do see a blank line in the 'connected devices' tab.

**Comment by collinlindgren** [comment]
Same issue here. Windows 10. Tried v1.4.0-b402e70, and also v2.0.0-e5637c1-2282. Infinitton Buttons are blank and it does not show up in Surfaces.

**Comment by Julusian** [comment]
Is this still an issue?
The usb logic has had a lot of changes since the last comment on this, and I think I remember seeing a similar issue for streamdecks being fixed in that time

**Comment by haakonnessjoen** [comment]
I just tested with current latest master branch, and it seems to work fine with my infinitton at least.

But when I downloaded the latest build from bitfocus.io, it is having some issues with sending graphics to the device. The two centermost buttons (11,12) gets the same page number in the top (11), but button 12 is not drawing completely on page changes. And other buttons are partially drawn etc. So a lot of weird update issues when changing page. If I adjust the starting position x, everything is drawn correctly, so it seems like it only happens when I change page using the buttons on the device. Not sure how we can start debugging this issue.

But no issues with it being detected at least.

**Comment by Julusian** [comment]
Did it work before I started making changes in the library last week? 
In other words, does it work with a couple of weeks old build?

**Comment by jermg77** [comment]
Hi Julian,

Just following up to let you know that since you spoke with Keith and added the Infinitton drivers to the 3.1.0 beta, I can confirm that it is not correctly working with my Infinitton on the Apple Silicon build. The device seems to be recognized in some way, meaning the Infinitton spash screen goes away, but there are only some random graphic lines in the top left button. Also, it does not appear to be listed in the Surfaces tab of the web GUI.

Let me know how else I can help!

-Jeremy

**Comment by haakonnessjoen** [comment]
I just tested the infinitton on my mac m1 on the develop branch, and companion did not recognize it at all, the device still has it's logo.

<img width="299" alt="image" src="https://github.com/bitfocus/companion/assets/416667/710f54f7-4c2f-4993-86d1-5fb1f52d82df">

**Comment by Julusian** [comment]
@haakonnessjoen develop wont see it, I havent merged the code there yet. beta might work though

**Comment by Julusian** [comment]
@jermg77 I've found I made a typo which could cause that. Maybe beta 6119 works better?

@haakonnessjoen This is in develop now too, although it could be broken for other reasons there due to other usb changes/refactoring

**Comment by jermg77** [comment]
@Julusian Just tried 6121, and Infinitton seems to be back in business. The only issue seems to be the same graphics drawing issue in 2.4.2 @krocheck was helping to report, where the button graphics seem erratic and half-drawn on incorrect buttons.

Thanks!

**Comment by haakonnessjoen** [comment]
Yeah, it's probably broken because of the changes/refactoring, I got this error on develop: `error Surface/Controller Failed to add "infinitton" device: TypeError: this.ipcWrapper.log is not a function`

On beta branch it is successfully loading, but the page button and the page down button is some times only rendered half (black on the rest of the button). I tried drawing every button red, and switching quickly between that page and the next, but I didn't see any more artifacts other than that the page button some times were rendered half. Now the last time I was able to reproduce it, the page button got the red color from another button. Maybe you are drawing multiple buttons at once. As far as I know, the firmware of the device doesn't support sending partial packets to multiple buttons at once. So if you are sending multiple packets for a button, you need to finish that before sending a new multi-part button update.

![infinitton](https://github.com/bitfocus/companion/assets/416667/d5bc3818-fb83-470a-8380-e648b687b983)

**Comment by Julusian** [comment]
Hmm.. I can't explain these drawing issues.. the code for this drawing has changed so little in the last couple of years, and it is not trying to do anything asynchronously.

Maybe something changed inside of `hidapi`/`node-hid` causing some subtly different timing between packets? Or something which only happens on apple silicon macs?

Maybe adding a sleep between each button draw will mitigate this? Even if this does help it wont be very durable

I'm not really sure how to progress on this without being able to trial and error things myself.

**Comment by jermg77** [comment]
@Julusian if it helps, I can say that this screen draw issue was not present on my previous intel based MacBook Air running the latest 2.4. It was only when I recently moved to an M1 air that I noticed this. Both on the Apple Silicon and the intel build running in Rosetta.

**Comment by Julusian** [comment]
@jermg77 to clarify, you were using the same version of companion there (eg 2.4.2 on both)? and its the same version behaving differently on intel to apple silicon?

**Comment by jermg77** [comment]
@Julusian I'm out of town without the intel machine at the moment, I'll have a look when I get home though and report back.

Thanks!

**Comment by jermg77** [comment]
@Julusian I’m back in front of both my Intel and M1 MacBook Airs and I can confirm they are both on 2.4.2 4911 (Intel and Apple Silicon builds respectively) and the button draw issue only appears on the Apple Silicon machine. This problem is also present on my M1 Mac mini. 

![IMG_4942](https://github.com/bitfocus/companion/assets/42151303/18eaa154-4c83-4956-980b-1225e58d4a77)


Let me know if I can provide more info for you.

**Comment by Julusian** [comment]
It is sounding like this is an issue inside of the hid library that only manifests on m1 macos. perhaps even a bug in macos.

I shall try and test some of the streamdeck models, perhaps it is possible to reproduce there with m1?

**Comment by haakonnessjoen** [comment]
Do you have one of the older 15 keys? They had very similar protocol to the infinitton, with raw image buffers etc. Maybe worth a try.

**Comment by krocheck** [comment]
@jermg77 one of our guys can get you one on the next show if you don't.  There's too many people running around to not have one there.

@haakonnessjoen I did have an M1 colleague with an original Stream Deck report the following related to 2.4.2: "[a] button will work for a while then suddenly it won't anymore and it paints a button from another page [while] presses no longer do anything."  At the same time he'd never seen the behavior @jermg77 reports on his original Stream Deck.  I can follow-up on his issue.

**Comment by jermg77** [comment]
@haakonnessjoen I do not have a Gen 1 Stream Deck 15 key. But I will be able to borrow and test one next week as @krocheck suggested. Just to keep things straight @krocheck my issue is with the Infitton, not Stream Deck. 

Thanks all!

**Comment by Julusian** [comment]
I have just tried a Gen 1 15 key, on an M1 mini (via satellite, but that shouldn't matter) and it is working fine no matter how fast I change pages

**Comment by Julusian** [comment]
I am suspecting the bug to be a race condition in the M1 HID stack, when mixing calls to `write` and `sendFeatureReport`.
The infinitton uses this for drawing: https://github.com/bitfocus/node-infinitton-idisplay/blob/eb7212eba7cfe23f7e4de837702f5ccf03746da7/index.js#L278-L287, with the `sendFeatureReport` indicating that a button has been drawn and should be displayed.

The streamdecks do not do this, and just use `write` for drawing. If it were an issue with just calling `write` it would be much more visible on other models, as for an XL each draw is 10+ calls, compared to the 2 for the original 15 key. (and the jpeg encoding of the XL and others would mean that wrong order of packets will result in garbage)

**Comment by Julusian** [comment]
It sounds like this is working now, but it has issues on just M1 mac which sounds like a os/hardware issue outside of our control. So I think we have done everything we can on this
