### ISSUE TITLE
CompanionPi Update Issue

### ISSUE THREAD

**Issue by cpuguru07** [bitfocus/companion#1115]
sudo companion-update fails on 2-3 week old CompanionPi install due to git pull conflicts (no local code modifications). Running git reset --hard cleared conflicts and allowed me to run git pull.

I had the same issue on a second CompanionPi. However, I recall that sudo companion-update did work on them initially because I ran that command after first boot and they ended up on different builds. (SD cards were imaged from same file, but deployed a few days apart.)

I have not done any local dev work that should have created these conflicts, but something changed in the local code after the initial companion-update that caused these conflicts.

**Comment by cpuguru07** [comment]
Ticket submitted per FB convo w/ @jarodwsams

**Comment by Julusian** [comment]
Do you know which files conflicted?
This happens sometimes if a new module doesn't commit the yarn.lock file, or something.

**Comment by cpuguru07** [comment]
I do not recall specifically, but I do recall seeing a warning about yarn.lock. The only two modules the two Pis have in common are pjlink and RokuTV, so I would assume it is probably that file in one of those modules.

**Comment by Julusian** [comment]
It could well be one of the other modules which you arent using.
No modules appear to have a rogue yarn.lock file in latest though, so I think this is fixed (for now) and is an issue that will crop up again.

Perhaps we can script something to do some cleanup to avoid problems like this where possible

**Comment by jarodwsams** [comment]
@Julusian, is it a simple matter of finding and deleting .lock files?

**Comment by bece65** [comment]
I am having the same issue , after i run   git reset --hard  i can run git pull  ... But companion doesn't start anymore, i am able to run run sudo companion-update fine but it's the same .
When i run sudo systemctl status companion i get this 
 companion.service - Bitfocus Companion (v2.0)
   Loaded: loaded (/etc/systemd/system/companion.service; enabled; vendor preset
   Active: failed (Result: exit-code) since Sat 2020-06-06 04:20:58 CEST; 10s ag
  Process: 626 ExecStart=/usr/local/src/companion/headless_ip.js 0.0.0.0 (code=e
 Main PID: 626 (code=exited, status=203/EXEC)

Jun 06 04:20:58 CompanionPi systemd[1]: companion.service: Service RestartSec=10
Jun 06 04:20:58 CompanionPi systemd[1]: companion.service: Scheduled restart job
Jun 06 04:20:58 CompanionPi systemd[1]: Stopped Bitfocus Companion (v2.0).
Jun 06 04:20:58 CompanionPi systemd[1]: companion.service: Start request repeate
Jun 06 04:20:58 CompanionPi systemd[1]: companion.service: Failed with result 'e
Jun 06 04:20:58 CompanionPi systemd[1]: Failed to start Bitfocus Companion (v2.0
lines 1-12/12 (END)...skipping...
● companion.service - Bitfocus Companion (v2.0)
   Loaded: loaded (/etc/systemd/system/companion.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-06-06 04:20:58 CEST; 10s ago
  Process: 626 ExecStart=/usr/local/src/companion/headless_ip.js 0.0.0.0 (code=exited, status=203/EXEC)
 Main PID: 626 (code=exited, status=203/EXEC)

Jun 06 04:20:58 CompanionPi systemd[1]: companion.service: Service RestartSec=100ms expired, scheduling restart.
Jun 06 04:20:58 CompanionPi systemd[1]: companion.service: Scheduled restart job, restart counter is at 5.
Jun 06 04:20:58 CompanionPi systemd[1]: Stopped Bitfocus Companion (v2.0).
Jun 06 04:20:58 CompanionPi systemd[1]: companion.service: Start request repeated too quickly.
Jun 06 04:20:58 CompanionPi systemd[1]: companion.service: Failed with result 'exit-code'.
Jun 06 04:20:58 CompanionPi systemd[1]: Failed to start Bitfocus Companion (v2.0).

Any ideas ?

**Comment by cpuguru07** [comment]
Yes, I had the same issue after running git reset --hard
I had to:
1. Run "sudo nano /etc/systemd/system/companion.service" to edit the companion service
2. Find the line "ExecStart=/usr/local/src/companion/headless_ip.js 0.0.0.0"
3. Add "node " ("node" followed by a space) after the = sign. Should be:
"ExecStart=node /usr/local/src/companion/headless_ip.js 0.0.0.0"
4. Ctrl + X to exit, then Y to save changes, then Enter to confirm
5. Run "sudo systemctl daemon-reload" to reload the service daemon
6. Run "sudo systemctl start companion" to start the Companion service

**Comment by bece65** [comment]
@cpuguru07 Thanks . 
I could update companion by another method : 
1. Run "sudo git checkout -f lib/instance_skel.d.ts lib/instance_skel_types.d.ts" 
2. Run "sudo companion-update"

**Comment by jarodwsams** [comment]
@cpuguru07 I've just published the new image for CompanionPi that should resolve this issue. Links are in the wiki (https://github.com/bitfocus/companion/wiki/CompanionPi-Documentation). Please let me know if you still experience this issue.
