### ISSUE TITLE
reset minimize after have enable it

### ISSUE THREAD

**Issue by sitosson** [bitfocus/companion#1127]
Please help me to reset the starting windows of Companion.
 I enable it by mistake.
I can't enable it back as a window, how mutch I even try by reinstall and other thing
Best rergards
Tommy Simonsson

**Comment by josephdadams** [comment]
@sitosson Can you provide an update and answer to my questions? If not, I'll close this.

**Comment by pdrwhitey** [comment]
It's a problem with my windows 10 also. Can't run program at all

**Comment by josephdadams** [comment]
Are you sure it’s not running in the system tray?

**Comment by pdrwhitey** [comment]
Thank you for your help. Works now.wr Sent from Mail for Windows 10 From: Joseph AdamsSent: Sunday, July 5, 2020 11:48 AMTo: bitfocus/companionCc: pdrwhitey; CommentSubject: Re: [bitfocus/companion] reset minimize after have enable it (#1127) Are you sure it’s not running in the system tray?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
