### ISSUE TITLE
Logic for devices

### ISSUE THREAD

**Issue by bustedbridge123** [bitfocus/companion#1138]
Would it be possible to add logic functions for devices?
ie, Panasonic PTZ camera tally light to auto turn on whenever the scene on the ATEM that the camera is in is turned on. At the moment you can make the stream deck keys interact with the states of devices, but not other devices.
Thanks!

**Comment by josephdadams** [comment]
Take a look at #651 for some input on this.

**Comment by dnmeid** [comment]
Logic is a big upcoming thing and it will be there in the future. Not sure though how to implement it in a way that it is easy, flexible and powerful at the same time.

**Comment by tim-barr** [comment]
I have two thoughts on how to meet this need.

Option1) New action for instance creators.  The creator of a current instance can select "set foreground color" and "set background color".  This "change colors" construct has been used by a lot of modules. 

For this option Companion would add the ability for instance creators to add another choice to each feedback option called "action".   However, the instance creator would have to add it to their setup.

a) The "action" could be limited to "push button" on Page X, Bank Y  (and optionally device Z).  So the feedback might include these "options" in the right column: Foreground color, Background color, input (for Atem), Press_Page, Press_Bank

b) A more advanced version would allow a dropdown of all the "internal:" functions in Companion.   However, this would then require another column of sub-options for the selected internal command.  Frankly since all that would be available via a hidden button somewhere, I don't think it is necessary.


Option 2) Global feature in Companion that would work on all Modules.  Obviously this would be even better as it wouldn't depend on instance creators having to change anything. 

a) Companion would automatically add selectors for "Press_Page and Press_Bank to the option box on all feedback choices.  (optionally add Press_Surface too).  If blank, these would do nothing.

b) Companion would add and "add action" to the options box of all feedback and a sub-option column as described in 1b above.  This could be limited to just "internal" actions to keep it more predictable as the sub-options would be known.

Just some thoughts.  I'm a programmer, but not an "instance creator".  :-)

**Comment by Julusian** [comment]
I think this will want to build on the idea I proposed in https://github.com/bitfocus/companion/issues/1187. With the modules exposing properties, it will be simple to do real comparisons on them.

The problem in the current flow is that for each feedback, the module developer has to add the same boilerplate of adding colour pickers, and if the condition is true, then return the color values. So if we were to let actions be triggerable from those, then every feedback would need to be duplicated to do that. Plus it would end up being executed multiple times, as there is no preserved state here.

But with feedback being replaced by properties, the core of companion can do a lot more with those values, and do the scheduler based on real values instead of comparing the string based variables

**Comment by tim-barr** [comment]
I did read #1187 and agree that having direct boolean testing against values would be far more powerful in the long run.

When I read the "solution needed" tag on this thread, I wanted to propose a potential shorter-term solution that tweaks existing functionality.  Maybe there is a benefit to both #1187 for those that can change their modules to expose properties, and my 2A option which would enable basic button push on the existing responses.

**Comment by Julusian** [comment]
This is now doable through #1186 with the help of #1604

**Comment by tim-barr** [comment]
Agreed.  Thanks everyone.
