### ISSUE TITLE
Show alternate text/visual when button pressed

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion#1205]
**Describe the feature**
Add a secondary button visual that would display when a button is down/pressed.
Include text, alignment, colors and picture.

**Is this platform dependent (windows, mac, ..)?**
No.

**Usecases**
Add a (different) dynamic variable the the 'down text' :
- for data that only needs to be checked periodically.
- for more specific details relevant to a button.
- easily change 'this' button's color when pressed

Currently, a button needs to know where it is (page/bank) to use 'Internal' change bank action. This makes buttons hard to copy.

**Comment by dnmeid** [comment]
Since this is beeing revisited atm, I have this ideea to make button states. Right now a button has only one "state", i.e. a set of colors and text and image. For backward compatibility I would make this state 0 in the future which is the default state. The you could add more states, maybe state 1 with a different text and different colors or a different picture. Now I think of a change state internal action, so you can change to state 1 if the button is pressed and state 0 if the button is released. You could even have more than two states and feedbacks could be used to change a state. Overall a quite elegant and flexible way to enhance buttons. And the coding effort should be not too much.
So what do you think?

**Comment by Julusian** [comment]
This is very similar to what I have been thinking about as a feedback and variables rewrite.

I think this would be good to have as a default state, then have additional override layers which can be selected like you propose.
This way, you can still define things once on the default and selectively change values with switching state. (eg, define the text once, but set a different png in each override state)

Long term, I would like to see this evolve into a more layer based system, with feedbacks set to enable a layer (with logical operators) instead of explicitly emitting a background and foreground colour. But that will become a bit of a mess to toggle like that via actions.

Also can we call this displayState (or displayLayers?) to clarify the purpose of this state

**Comment by Julusian** [comment]
With #1571, this could be achieved with a new internal feedback to detect the buttons pressed state

**Comment by Julusian** [comment]
There is an internal feedback 'When button is pushed' which does this now

https://github.com/bitfocus/companion-module-bitfocus-companion/commit/fa926cc5f12d5704b5347511664601b5cd1f1c3f

**Comment by istnv** [comment]
@Julusian I was going to offer to add that after you put in the feedback toggle :)
Well done!
