### ISSUE TITLE
[BUG] A Java Script error occured in the main process - Uncought Exeption - Syntax error: unexpected token

### ISSUE THREAD

**Issue by ce1958** [bitfocus/companion#1221]
I have  Companion v.0.2.0-47823d0-2493

Direkt while starting the error occurred.
![image](https://user-images.githubusercontent.com/71131605/92922820-b3ca1c80-f436-11ea-90bb-0d82bd5dd1ef.png)
Worked before several days without problem.
![image](https://user-images.githubusercontent.com/71131605/92923000-04da1080-f437-11ea-8a40-2a4b19a42891.png)

**Comment by charleswwelch** [comment]
I have the same problem. On the same version companion-2.1.0-47823d0-win64-signed. The software has worked reliably up until today (or sometime since Monday Sept 7). I've removed and reinstalled Companion, I've also removed and reinstalled the Elgato software although I don't use it. I've also tried updating Java and following some other suggestions I found online for this generic error: I removed the %appdata% and %localappdata% files for Companion. Now I'm worried I've wiped my current configuration and may have to roll back to an old backup (foolish of me not to have saved the current config). With all of this, I still receive the error and cannot find the surface when I connect to the GUI. 

I also can't import the old backup config to use the GUI without the physical device. I just get an open window and when I select the config, nothing happens. I also can't add instances by clicking "add by category" or "add by manufacturer".

All that being said, I really look forward to you guys helping resolve this because this software is AWESOME. It makes my life and other volunteers lives so much easier! Thanks for your hard work on it, and for working to help me find a solution. I am ready to help however I can, but that probably doesn't mean much.

**Comment by ce1958** [comment]
Now it happened again at my second notebook too. He needed reboot and after that when I startet Companion there was a fault of starting to many instances of companion and now it is not starting any more !
I have the same error!

Is it possible, that companion dont like hard boots while working?

**Comment by ce1958** [comment]
When I tried to click several times starting companion I get this error message:

![image](https://user-images.githubusercontent.com/71131605/93080043-6398c780-f68d-11ea-991b-a46f0a459925.png)
Maybe it helps ...

**Comment by willosof** [comment]
Hi guys, can you confirm that this happens in the latest beta build as well?

Also, which modules are you using? :)

**Comment by willosof** [comment]
And can you confirm that this is also happening in the last beta builds? (BETA below the download button)

**Comment by krocheck** [comment]
First problem ... latest builds failed: https://github.com/bitfocus/companion/actions/runs/249761264

Companion v2.1.1 (2.1.1-2de1549-2569) is running for me on Windows 10 Pro 2004.  I haven't seen this issue with the stable release, as I have it on a number of Windows 10 machines.  @willosof part of the stacktrace mentions Sentry.  That's the only thing that stands out because whatever it is fires from an emit.

**Comment by ce1958** [comment]
![image](https://user-images.githubusercontent.com/71131605/93102041-52f74a00-f6ab-11ea-9739-c06a8113797a.png)
I confirm

**Comment by krocheck** [comment]
One clue here might be that the interface list isn't populated yet in that screenshot.

**Comment by ce1958** [comment]
![image](https://user-images.githubusercontent.com/71131605/93104160-c8fcb080-f6ad-11ea-88c1-b0d1c466995d.png)

Can´  t snip the GUI Interface List (Is it what you mean?)

**Comment by charleswwelch** [comment]
Hi guys,

Here are the screenshots of the problem I am seeing (below). Let me know if
you are looking for something else.

Regarding the snip from Christoph previously, I also have an empty list of
Connected Devices, and when I rescan USB, nothing is found. However if I
try using the Elgato software, it is able to connect. I'm not sure if these
problems are related or separate issues.

William - what do you mean by modules? I am using the StreamDeck XL (it is
about a month old), previously with Instances of PTZOptics Cameras, OBS,
ATEM mini and ProPresenter. None of those are populating currently.

[image: image.png]

[image: image.png]

[image: image.png]
Charles Welch

**Comment by krocheck** [comment]
@charleswwelch attaching images via email response unfortunately doesn't work.  Please visit the issue's page on Github to attach your screenshots.

**Comment by charleswwelch** [comment]
> @charleswwelch attaching images via email response unfortunately doesn't work. Please visit the issue's page on Github to attach your screenshots.

not sure if an alert is sent when I update my previous post. I have attached the images inside of the issue's page on Github. If I'm still not getting it done, let me know.

**Comment by willosof** [comment]
I see the screenshots fine :) All good, but it looks like you're still on 2.1.0, and not on 2.1.1 beta. There's a few failed builds, but build 2569 has all platforms - I don't know why you pointed that out @krocheck? I don't see how it's relevant to this case.

**Comment by krocheck** [comment]
Perfect.  Thanks! ... no, didn't get an alter on that.

**Comment by willosof** [comment]
@charleswwelch Can you please make a zip file of the folder %USERPROFILE%\AppData\Roaming\Companion and upload it here?

**Comment by charleswwelch** [comment]
see here. I have included two. The one dated yesterday I deleted (but copied before deleting) as I mentioned above in my own troubleshooting efforts. Hopefully this one still has some historic useful info. The one dated today is on the fresh install that I did yesterday and is what I am currently running.

PS - I have tried to install the newest BETA from above, but am not finding it at the link provided.

[Companion Profile 091420.zip](https://github.com/bitfocus/companion/files/5220382/Companion.Profile.091420.zip)
[Companion roaming profile 091320.zip](https://github.com/bitfocus/companion/files/5220383/Companion.roaming.profile.091320.zip)

**Comment by ce1958** [comment]
Hi Wilosof,
I deinstalled Companion, renamed %USERPROFILE%\AppData\Roaming\Companion folder and installed again.
It worked!
So the problem is, that at deinsatllation the %USERPROFILE%\AppData\Roaming\Companion was not cleaned. In this folders is the problem.

**Comment by ce1958** [comment]
[Xompanion.zip](https://github.com/bitfocus/companion/files/5222685/Xompanion.zip)
Here isa my renamed old %USERPROFILE%\AppData\Roaming\Companion

**Comment by willosof** [comment]
Both @charleswwelch and @ce1958's /db files looks corrupted. This is new, but nothing has happened in that code for a while now, I think. Could it be something else? Do you guys use any particular anti virus or security software?

**Comment by ce1958** [comment]
I use AVG AntiVir.
At my computers it was damaged because of resetting the computer.
At the first Notebook because he mostly stuck in performance I did a reset.
The second Notebook got a Errorpage of Windows and rebooted.
Afterwards the Companion Problem occured.

**Comment by charleswwelch** [comment]
I have already tried re-installing after deleting the app data folder, but when I did it again today and installed the BETA version, everything is back to normal! Thanks!

I just use the standard Windows Security software on this PC. One thing I should have mentioned is that we did a swap of the graphics card about a week ago and that seems to be when the problem started. 

One additional question though, since I do have the original app data folder from the issue point, is there a way to recover my old button configuration from that folder? Like I mentioned, I made the boneheaded move of not exporting those settings recently and my most recent config backup is about 30 days old and I've done a lot of tweaking since then. Thanks for any help on this one also! Again, this software is awesome!

**Comment by jayakaran** [comment]
Had this issue today. Renamed %USERPROFILE%\AppData\Roaming\Companion and relaunched companion, imported the old settings I had backed up and restarted companion. Was good to roll. Discovered the issue 5 minutes before service and had it working 10 minutes in while I was at home on a day off.

**Comment by rkaplins** [comment]
This solution of uninstalling Companion, renaming %USERPROFILE%\AppData\Roaming\Companion folder, and then reinstalling  the also worked for me.  My only regret is that I wish I had backed up my settings before so that I did so because I have to set it all up again now.

**Comment by paulkostromitin321** [comment]
This problem also occurred with me, as soon as I updated my graphics card.

**Comment by jabbermouth** [comment]
This just happened for me too.  I'm using the latest version (2.1.4) on Windows 11. My machine crashed and then, when it came back up the JavaScript error was showing.  I uninstalled and reinstalled Companion and everything works again.  Windows 11 has been on since launch and, until this, no crashes.  I only got a Stream Deck and started using Companion a few days ago.  It could be coincidence of course but I thought it worth including.

**Comment by pdonut** [comment]
I am having this same issue, using the latest version 2.1.4 running on Windows 10 Enterprise.

**Comment by hgy59** [comment]
seems to be related to https://github.com/bitfocus/companion/issues/159
had a `db.corrupt` and `db.bak` file filled with zeros in the user appdata (programdata/Companion).
After removing the old programdata and new installation, companion runs again.

**Comment by Pauweltje** [comment]
2 Years gone by, and still having this making me pissed off, error! What a useless piece of software! and bunch of second-hand "programmers"

**Comment by josephdadams** [comment]
@Pauweltje did that make you feel better?

**Comment by JTF4** [comment]
> seems to be related to https://github.com/bitfocus/companion/issues/159
> 
> had a `db.corrupt` and `db.bak` file filled with zeros in the user appdata (AppData\Roaming\Companion).
> 
> After removing the old programdata and new installation, companion runs again.
> 
> 
> 
> Note: configuration is gone, so be sure you have a backup of the companionconfig file.
> 
> 

Hey @Pauweltj! 

I believe the fix for your issue was discussed a little earlier in this bug report. I've linked it here for your reference. I hope that helps!

**Comment by Pauweltje** [comment]
> @Pauweltje did that make you feel better?

Yes very, but the error still excists!

**Comment by Pauweltje** [comment]
> > seems to be related to #159
> > had a `db.corrupt` and `db.bak` file filled with zeros in the user appdata (AppData\Roaming\Companion).
> > After removing the old programdata and new installation, companion runs again.
> > Note: configuration is gone, so be sure you have a backup of the companionconfig file.
> 
> Hey @Pauweltj!
> 
> I believe the fix for your issue was discussed a little earlier in this bug report. I've linked it here for your reference. I hope that helps!

That did not help....

**Comment by Pauweltje** [comment]
I am gonna work with a macrorecorder, and everytime that error pops-up, it will be automaticly closed!
Problem solved!

**Comment by josephdadams** [comment]
Glad you found a workaround!

**Comment by lpsink** [comment]
> When I tried to click several times starting companion I get this error message:
> 
> ![image](https://user-images.githubusercontent.com/71131605/93080043-6398c780-f68d-11ea-991b-a46f0a459925.png) Maybe it helps ...

This is all I get when trying to run Companion Satellite
