### ISSUE TITLE
Feature: Master-Master replication between companion daemons on network

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#125]

**Comment by willosof** [comment]
Maybe like MAnet where you can create a session and the others can join :)

**Comment by willosof** [comment]
MAYBE this will be bitnet.

**Comment by Julusian** [comment]
In the name of trying to reduce the number of open issues, I am going to close this.

While I agree it does sound like a cool feature to have, I can think of many many challenges with it that make me want to stay away from doing it.

* Will every master be connected to every device? What about devices that have connection limits?
* How will changes be synced? What happens if both masters have edited the same thing and there is a conflict?
* If two masters are apart for a long time, should we try to consolidate again? I'm thinking two laptops which were setup to replicate at one event, then they went to different shows and noone disabled replication, then they go to another show together.

So this sounds like a lot of work that will change a lot of the backend of companion and make it all much more complex to handle these cases, and make everything complex as it will need to be coded to make sure it will replicate and consolidate predictably.

Anything master-master scares me because of this, I imagine this is why some of the big replicating databases have a single primary.
