### ISSUE TITLE
BUG: grandMA user other than administrator

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion#129]
**Describe the bug**
Changing to an other user than administrator seems not possible.

**Expected behavior**
When creating a new user with the same rights as administrator, login is not possible. switching to administrator is no problem

**Comment by evenboberg** [comment]
I also tested it with both administrator and different users with and without password without any problems. Only way I can make it not to work is after rebooting or restarting the software, because you have to logg in again.

To use the Telent remote you need equal or higher "user rights" than "Program".

**Comment by JeffreyDavidsz** [comment]
Thanks for the heads up, I'll try different user rights (now only tested admin and play).

**Comment by willosof** [comment]
This can't really be a companion bug, and needs to be a MA rights thing. We just provide username and password. no magic tricks involved :)
