### ISSUE TITLE
Version 2.1.1 crashes when VLC opens[BUG]

### ISSUE THREAD

**Issue by malcolmtaylor1** [bitfocus/companion#1300]
Using Compaion version 2.1.1 crahses whenever I open VLC on a Win10 PC.

**Comment by willosof** [comment]
2.1.2 released

**Comment by astellingwerf** [comment]
My sense is that this issue was not fixed. I still have Companion 2.1.2 (f4bcaf3-2679) crash when I launch VLC.

**Comment by McHauge** [comment]
did you add the password to the vlc instance?

**Comment by McHauge** [comment]
also please try the newest beta build, this might be fixed in those, there has been a lot of actions back and fourth latly

**Comment by istnv** [comment]
In that version, you also need to set the password in VLC before adding the VLC module in companion.

**Comment by astellingwerf** [comment]
> did you add the password to the vlc instance?

Where is it documented that that's a requirement. Even so: Why would Companion need to crash if I don't? Can't the plugin and companion framework gracefully handle the non-compliance?

**Comment by istnv** [comment]
The documentation describes where to set the password in VLC. The 2.2 releases fix this and several other issues. It was discovered after the 2.1 release that VLC 3+ requires a password. The companion module asks VLC for a JSON status report, then VLC incorrectly sends HTML when there is no password, which 2.1 was not expecting.

**Comment by astellingwerf** [comment]
The VLC module allows me to store the configuration without a password. The label says "(required)", but it's not enforced. If I don't provide it and store the configuration, and launch VLC 3 (which also doesn't enforce the presence of a password in its Settings UI), the Companion app crashes.
Would it help to add a `regex: self.REGEX_SOMETHING` on the password?

I can imagine that a HTML response instead of a JSON response would cause unexpected behavior, and I'd understand if I can't use the impacted module because of it, but why does it crash both the VLC module and the Companion app? Can I use Companion in production? Is Companion resilient enough to cope with less than perfect modules?

**Comment by istnv** [comment]
As I said, that and other issues are fixed in 2.2 along with other improvements. The VLC module was not fully ready when 2.1 was released. I'm not in charge of backporting things to 2.1 but I try to provide a method to make it work.
Also, REGEX_SOMETHING does not actually enforce something that something is input.
