### ISSUE TITLE
import configfile in excel to edit buttons

### ISSUE THREAD

**Issue by fdebeer** [bitfocus/companion#1339]
It would be nice to have the option to save the configfile as an excel file to easy and fast edit buttons in excel with every button on a new row

**Is this platform dependent (windows, mac, ..)?**
no

**Usecases**
Sometimes i like to edit the button names i made, but for this i have to click every button individually
i would like to use the configfile for this, so i can in one file edit the buttons and import the file back in companion
When looking at the configfile, it is commaseperated, so it should be possible to import it in excel. but all buttons are in one row and not every instance is easy to find
It would be nice if every button start in a new row when importing the configfile in excel with all the instances of this button.
it is also easy to edit small changes in buttons like presetnumbers for ptz

**Comment by Julusian** [comment]
How would you expect to see the data arranged?
The problem I see is that the button has a few properties, then it can have many actions and feedbacks.
Each of the actions and feedbacks have a variable number of properties.

So the actions and feedbacks will want to be their own rows, and will be tied back to the button somehow?

From a more technical side, this will probably require quite a change in how the data is imported, as I dont think any validation is done currently. This is fine for now as it isnt intended to be manually edited, but if we do export to an editable format then upon reimporting it should be checked to look valid. Otherwise it would be easy to accidentally change a number to a string (actually excel will probably do type conversions we dont want it to), which could then cause companion to crash upon executing that action. Or various other data issues could be introduced

**Comment by josephdadams** [comment]
It would be safer to create a new GUI interface for mass editing like this so that we maintain data validation control.

**Comment by fdebeer** [comment]
First of all, i'm not a programmer...
> How would you expect to see the data arranged?
per button on 1 row
> The problem I see is that the button has a few properties, then it can have many actions and feedbacks.
> Each of the actions and feedbacks have a variable number of properties.
> So the actions and feedbacks will want to be their own rows, and will be tied back to the button somehow?

i dont think there are variables on a button, just commands. the variables it recieves  and the feedback is from a device.
this can change the look of a button, but i dont think this is saved in the configfile.
but again, i'm not a programmer :)

> From a more technical side, this will probably require quite a change in how the data is imported, as I dont think any validation is done currently. This is fine for now as it isnt intended to be manually edited, but if we do export to an editable format then upon reimporting it should be checked to look valid. Otherwise it would be easy to accidentally change a number to a string (actually excel will probably do type conversions we dont want it to), which could then cause companion to crash upon executing that action. Or various other data issues could be introduced

Looking on the configfile now, it only contains text between brackets. i think maybe its a dump of the database. 
i think its more quite a change in how the data is exported to make it easy to edit

**Comment by tim-barr** [comment]
What about switching the data storage from CSV to XML.  XML handles a variable number of elements vary well, and can also represent elements(Button), sub-elements (actions, feedbacks), and fields within the sub-elements.  A global setting could determine which method of storage is used.  Or maybe this is just something for 3.0.

**Comment by Julusian** [comment]
@tim-barr the exported files are currently json, and I dont think that changing to xml would provide any benefit

**Comment by tim-barr** [comment]
Thanks @Julusian .  I didn't realize the data was already in a "self-describing" data format which also supports hierarchical data structures.

**Comment by kcwvc52** [comment]
Obviously something that needs to. be figured out and fixed. because this would be a huge time saver

**Comment by kcwvc52** [comment]
without congress approval? nope.
