### ISSUE TITLE
[BUG] Unable to open 2.2.0 builds on Mac

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#1340]
**Describe the bug**
Unable to open 2.2.0 builds downloaded from https://bitfocus.io/companion/download/builds/ on macOS, 10.15.7 or 11+

**To Reproduce**
1. Download dev build from https://bitfocus.io/companion/download/builds/
2. Attempt to open on macOS
3. Error dialog

**Expected behavior**
Companion opens.

**Screenshots**

Big Sur
<img width="258" alt="Screen Shot 2020-12-22 at 10 09 01 AM" src="https://user-images.githubusercontent.com/50299051/102909103-153e5600-443e-11eb-9bf5-2a3dd5de5a83.png">

Catalina 
<img width="357" alt="Screen Shot 2020-12-22 at 10 12 19 AM" src="https://user-images.githubusercontent.com/50299051/102909179-30a96100-443e-11eb-84a2-39aec409e6eb.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser n/a
 - Companion Version every build **after** companion-2.2.0-44c1e6d-2676-osx.zip

**Additional context**

**Comment by Julusian** [comment]
That is every build after the electron upgrade.

Is it just that it is not signed so you have to command-click or something to force it to be allowed?

**Comment by bryce-seifert** [comment]
It's a slightly different error. That error reads like this, and works with a ctrl + click.
<img width="261" alt="Screen Shot 2020-12-22 at 11 56 45 AM" src="https://user-images.githubusercontent.com/50299051/102918747-22167600-444d-11eb-8030-505954ccc050.png">

With the new builds, ctrl + click returns the same "can't be opened" error.

**Comment by MeestorX** [comment]
I can reproduce this problem.
If you'd like the latest build, you can get it from my site. It's in a installable DMG instead of .zip file and it's signed so you shouldn't have any problem. You will have to register, but it's free.
www.checkcheckonetwo.com

**Comment by Julusian** [comment]
@MeestorX what did you do differently for your builds?

**Comment by MeestorX** [comment]
Sorry, I have no idea how bit focus is doing their builds. I do mine from source.

**Comment by Julusian** [comment]
Looks like just a `yarn run macdist` then a script which finds, renames then uploads the output. Which for mac is looking for a zip file.
I can see there is a dmg right next to that zip, so perhaps the script should be uploading that instead?

I dont see anything explicit about signing, so unless electron-builder is handling that perhaps something needs to be done there too?

**Comment by MeestorX** [comment]
On my Mac, I just run `yarn dist` and away it goes, creating a lovely signed DMG.
Since electron-build now creates a dmg file, you should stop using .zip files, IMHO. DMG is the approved distribution container as per Apple.
Mine is signed because I have a developer license. Not sure if whoever is building the Mac versions at bitfocus has a developer license?

**Comment by Julusian** [comment]
All the beta builds are autobuilt by github, and are not being signed with a developer license.
The release builds are done manually so that they are properly signed

Build 2743 is publishing the dmg now. Could someone test it to see if it behaves any better.

**Comment by MeestorX** [comment]
Seems to have done the trick. Still needs the ctrl-click (right-click) open, but that's to be expected until you sign it.
![image](https://user-images.githubusercontent.com/29129658/102942974-06729600-4474-11eb-832e-981b178dc33e.png)

**Comment by Julusian** [comment]
Perfect. I shall do some research into what our options are for signing. I think I remember the apple presentation about the arm machines requiring everything to be signed in some form

**Comment by MeestorX** [comment]
Apple's cracking down. Luckily most people using this software know about the right-click trick, but I used to have people all the time not want to run my beta builds because they thought their computer was going to explode. Big Sur probably cracked down even harder.
Luckily for me, Electron-Builder now DMG and signs the packages. Such an amazing tool.

**Comment by JeffreyDavidsz** [comment]
I switched to electron-forge but it should be possible to sign each build with electron-builder (I do that also for vicreo-hotkey)

**Comment by MeestorX** [comment]
What's the advantage of electron-forge over electron-builder?

**Comment by JeffreyDavidsz** [comment]
It's just an other builder, but it happens for me there where some tutorials how to use it with certificates for windows and osx

**Comment by MeestorX** [comment]
Copy. I didn't have to do anything. No idea when electron-builder was updated, but all of a sudden when I ran `yarn dist` out popped a signed DMG. Didn't do that a few months ago.
My guess would be that if the dev machine has an active certificate, it just finds it and uses it, but who knows? I wouldn't have known how to tell EB to use it anyway, it just did it in my case.

**Comment by bryce-seifert** [comment]
> My guess would be that if the dev machine has an active certificate, it just finds it and uses it, but who knows? I wouldn't have known how to tell EB to use it anyway, it just did it in my case.

Seems like that's what it is.

> On a macOS development machine, a valid and appropriate identity from your keychain will be automatically used.

[https://www.electron.build/code-signing](https://www.electron.build/code-signing)

**Comment by Julusian** [comment]
electron-builder got updated in 2676 at the same time as electron and some other things broke

**Comment by Julusian** [comment]
I have just tested this with the latest build and I do have to do a 'right click; open' then it is will open, and subsequent opens can be done with a double click.

I don't think that signing the beta builds is something that can realistically be done without a dedicated developer id generated for it, so that doesnt sound likely or worthwhile doing right now.
The releases are signed, and that is what is recommended for most users to run.

**Comment by MeestorX** [comment]
> I don't think that signing the beta builds is something that can realistically be done without a dedicated developer id
Just curious why that is??
Are you building on a different machine than the one that has the license? Cannot multiple machines have the same developer license?

**Comment by Julusian** [comment]
The builds are done automatically on a pool of machines owned by github. A developer license can be added to them, but I wouldn't be comfortable adding my own developer license there because it will be almost impossible to audit what was signed with it.
I think am being overly paranoid/cautious here, so maybe it should be done for both mac and windows as they both semi-care.
