### ISSUE TITLE
[BUG] Companion does not see any Stream Decks  

### ISSUE THREAD

**Issue by loftdweller** [bitfocus/companion#1355]
Never had a problem before, and now that I've gone to 2.1.2 on Mac / Mojave - Companion sees Vmix etc but not any Stream Decks. All firmware are current etc. 

Error is:

USB(undefined): Found device, but no access. Please quit any other applications using the device, and try again.

Mojave 10.14.6
Chrome 87.0.4280.88
Companion V2.1.2 (2.1.2f4bcaf3-2679)

Have tried two different size stream decks as well - normal and XL. No luck getting either to connect.

**Comment by WesleyvN** [comment]
Hi Loftweller, 

I have the same at the start (mac user) the issue at my side was that the Elgato software is directly connecting to the Stream deck. 

Please try to instal the companion Plugin for the StreamDeck or try to uninstall the Elgato Software!

Please let us know if the issue is solved(or not)!
