### ISSUE TITLE
Anyone had intrusions while using Companion?

### ISSUE THREAD

**Issue by alfred-hitch** [bitfocus/companion#1366]
We are investigating about a double intrusion in several computers running Companion and placed in different locations and under different providers. 

Who entered in all of the computers seems to know well Companion. Companion is the unique thing in common between our computers (each computer is from a different users, with different names, IP, domain, services, objectives).

**Comment by josephdadams** [comment]
What was the intrusion?

**Comment by Julusian** [comment]
I can't say I'm surprised.
It did occur to me a while back that anyone with webui access will be able to run arbitrary scripts on the companion machine, with the privileges of the user running companion.
And the vicreo hotkey listener is similar and will let anyone on your network run scripts.
I havent had any good ideas on how to make it secure without either removing the shell commands options, or implementing a proper security model which is a large task and to do properly will probably break controlling companion over tcp/http/osc.
I guess that to properly secure companion currently will require properly firewalling the machines and if remote webui access is needed proxying it and adding authentication there

**Comment by alfred-hitch** [comment]
I edited the title because it seems like I was saying that companion is the breakable part of the system. I have to sat this issue is only for investigating if other users had same problems while running Companion.

@Julusian Yes, the first thing to do is to put some security in front of Companion, something that we did not because of the effort and because this machines are only for testing purposes. I was thinking to put Apache proxy (I think it has a better and simpler implementation of wss proxy despite nginx, for example) and then protect the emulator with password access. But, if I protect UI with password I don't know if it would be possible to control Companion via GET requests without adding some auth header (and everything it would require in order to make it possible). 

@josephdadams Someone was able to know the IP addresses of those machines (from public) and knew that they were using companion. This "person" also knows what companion is and how it works because he totally changed buttons and other functionalities within minutes. On all of the machines. 
The emulator and button pages were protected by pin but - our fault - the admin UI was accessible because our horrible provider has to open a DMZ on each machine in order to open ports on public (we did not set a firewall because of the fast testing). 
My question was if Companion is able to send some information from users to some server collecting info (maybe debug purposes) but i didn't find anything about this. 
The thing that made me thinking about Companion is the fact that that user knows Companion, knows all the machines running Companion and only edited Companion functions (not other services which were running - and exposed - on those machines). 

**Companion still is a really great and well done project, I don't think is responsible for this intrusion** but just wanted to know if anyone else here was, in any moment, in this kind of situation.

**Comment by josephdadams** [comment]
@Julusian what about an allow/deny list in Companion for the base listeners (tcp/http/osc) and GUI? With 127.0.0.1 always being accessible? If it was disabled by default, interested users could go in and add entries as needed.

**Comment by benjaminpick** [comment]
If this is regarded as a security-related bug or not depend on the expectations of the user. Thus, it would be good if the software is configured as secure as possible by default, e.g. "shell commands are disabled by default, only those who need it enable it", and "show a warning when enabling the GUI on a non-local IP address for the first time".

IMO, it would be amazing if without a password, you can only use the buttons that are configured, so the web access can only be used to trigger the actions that the user has in mind when he configured the device - I would like to password-protect the whole admin GUI as we have many devices in our network and old firmware is always a security risk. Whilelisting IPs could also be a way to go, but not so convenient in our scenario because the clients are DHCP clients and thus their IP might change, whitelisting the MAC-address would be more appropriate (but more complicated for beginners to do, unless the interface suggests the devices that one can whitelist or not).

**Comment by spoelstraethan** [comment]
I feel like setting up an Oauth2/zero trust authentication via reverse proxy is probably slightly outside the scope of Companion's functionality, but making it operate behind any of the many free options for this type of authentication would be ideal, especially if it can appropriately track sessions and avoid token replay attacks.

**Comment by thedist** [comment]
Most security related issues can be handled by observing best practices and controlling access to Companion to begin with. If you have lax network security and open a Companion server up to the internet for the entire world to access then you've got much more significant security concerns than Companion not having OAuth.

**Comment by spoelstraethan** [comment]
> Most security related issues can be handled by observing best practices and controlling access to Companion to begin with. If you have lax network security and open a Companion server up to the internet for the entire world to access then you've got much more significant security concerns than Companion not having OAuth.

I totally agree, but typically these reverse proxies expose only the web interface and don't manage port access, but as I've learned in another issue, the web interface is the ONLY one that honors the specific IP binding in the GUI config, everything else binds 0.0.0.0 so you have to use other layers of firewalling/isolation to keep stuff from touching Companion inappropriately within your network.

This makes the upcoming Firewalla feature of VqLANs where you can group systems and they treat your network as a Zero Trust environment and only explicitly allow communication based on rules and/or group memberships a HUGE weight off my shoulders when it comes to Companion. Otherwise I probably would have had to spend a bunch of cycles per OS I use it on to block all traffic except via certain requests.
