### ISSUE TITLE
Button Press followed by Button Release action doesn't take affect? [BUG]

### ISSUE THREAD

**Issue by bmadtiger** [bitfocus/companion#1376]
**Describe the bug**
It seems that Button Press action doesn't actually set the correct latch state on a button? So the first Button Release action on the affected button doesn't trigger, even though a physical press of the latched button (or even a subsequent Button Release action on the same button) does trigger the release.

**To Reproduce**
Import attached config file (to page 20 or adjust the page in the actions and release-actions in the config)
This config simply sets the button text to ON and OFF to match the latch state for buttons 20.2, 20.3 and 20.3 and then also toggles the state of other buttons as listed below.

**Expected behaviour**
 - When pressing button 20.2 - button 20.3 should be turned off
 - When pressing button 20.3 - buttons 20.2 and 20.4 should be turned off
 - When pressing button 20.4 - button 20.2 should be turned on (which should then turn button 20.3 off)
 - When pressing button 20.3 again - buttons 20.2 and 20.4 should be turned off (as above)

**Actual behvaiour**
 - When pressing button 20.2 - button 20.3 is turned off (correct)
 - When pressing button 20.3 - buttons 20.2 and 20.4 are turned off (correct)
 - When pressing button 20.4 - button 20.2 is turned on and button 20.3 is turned off (correct)
 - When pressing button 20.3 again - buttons 20.2 is still ON (incorrect) and button 20.4 is turned off (correct)

**Desktop (please complete the following information):**
 - OS: Windows 10 (2004) 64-bit
 - Companion Version 2.1.2

[Page20.json.txt](https://github.com/bitfocus/companion/files/5825544/Page20.json.txt)

**Comment by istnv** [comment]
This is a by-product of making a **latch** button work. A physical press on a button will always be followed by the physical release. So a **latch** button needs to ignore the following release otherwise it would not stay on.
The current internal messaging between 'A button is pressed' and 'execute the down actions' does not know _where_ the down press came from (web/osc/emulator/streamdeck) and always assumes there will be a corresponding _up/release_ to be discarded.
The non-physical programmed  _press_ (without release) needs to be able to indicate there is no following release to discard.

**Comment by bmadtiger** [comment]
Okay, so if I use a *Button Press & Release* action instead of the *Button Press* - because it is a latch button it won't execute the *Release* action? (And then the subsequent *Release* action will work?) So what is the point of the *Button Press* action vs *Button Press & Release* action? By the naming of the two actions it seems one will work for latch buttons where as the other will work for non-latch buttons?

**Comment by McHauge** [comment]
If you want to press and hold a button, eg used alot with ptz's. Then you can have one press the button and another release it again, or you could use the pres and release in one go, if you just want an instant press and release. But this changes a lot if you use them to activate a latch button, like istnv explained

**Comment by bmadtiger** [comment]
@McHauge That makes sense. I'll check this out and make sure it is working as expected now I understand it better.

**Comment by istnv** [comment]
The latching button will prevent multiple presses and multiple releases. So if a button is already pressed/latched, the down actions do not re-run. Same thing for multiple up/release if the button is already up.
@bmadtiger Your idea _should_ work but does not because the current logic improperly ignores a valid release. There is a point where second press/release leaves button 2 out of sync.
@McHauge The last part of my comment is what needs to be done to make this work (without disrupting other operations). The automated press-only needs to indicate that the following release should not be discarded.

**Comment by istnv** [comment]
Recent work on the `This button` feature also included a fix for this.
The described configuration works as expected in the latest builds.
