### ISSUE TITLE
Ignore connected xkeys

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion#1421]
Create a setting that will ignore a connected xkeys. This to prevent "stealing" it from other applications.
#1196

**Comment by QRUXEL** [comment]
Would just like to second this request, I'm having a lot of issues with our other custom software that uses xkeys. 

IMO, wouldn't it make sense to have all inputs (including streamdecks) be like any other equipment on the "Instances" tab? e.g. that you would have to add the different surfaces that you want companion to use?

**Comment by JeffreyDavidsz** [comment]
It's in the latest build. On the surface tab you can disable the xkeys to be used in Companion

**Comment by kd8ssq** [comment]
The option to disable the xKeys connection doesn’t seem to be fully working.  The brightness control is still overriding the brightness on my xKeys XK-24 and we’re having our preconfigured vMix commands (which run directly from vMix) behaving strangely.  I’m wondering if Companion is still trying to override.

**Comment by JeffreyDavidsz** [comment]
Each command coming from the xkeys will be ignored (when you set the option). But it is still possible to set the brightness yes.

**Comment by QRUXEL** [comment]
> Each command coming from the xkeys will be ignored (when you set the option). But it is still possible to set the brightness yes.

You make it sound that it's a feature and not a bug? =) Is it possible to have it not touch the device at all if it's set to ignore? Since our other software that uses the xkeys only sets the colors once the program starts, we have to restart the software after we start companion which is a bit annoying. 

(I would personally prefer if it's an opt-in to use an xkeys device rather than the current way of "capture ALL the things!" =) )

**Comment by JeffreyDavidsz** [comment]
I think I can make it scan but ignore, need to test it because you would want to be able to enable it and therefore see it in the list of devices ;-)
