### ISSUE TITLE
Request: Lightware OPTC fibre extender input switch commands LW3

### ISSUE THREAD

**Issue by dnny** [bitfocus/companion#143]
**Describe the feature**
Support for Lightware OPTC fibre extenders input change. LW3 protocol.
As the unit has two hdmi inputs, these two commands would allow switching between them.
Hardware:
https://lightware.com/hdmi20-optc-tx220-pro

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
page 46 at section 6.6.2 in the manual:  https://lightware.com/pub/media/lightware/filedownloader/file/HDMI20_OPTC_series_Users_manual_v1_1.pdf

TCP/IP communication port is 6107
All commands are terminated with a carriage return (Cr, ‘\r’) and line feed (Lf, ‘\n’) pair.

The two commands would be:
input 1 to output
CALL /MEDIA/VIDEO/XP:switch(I1:O1)

input 2 to output
CALL /MEDIA/VIDEO/XP:switch(I2:O1)

**Usecases**
We could feed the projectors two signals, main and spare, and would be able to switch the input from companion if needed.

This is an LW3 protocol that is also used in other Lightware matrixes like the 8x8 and 16x16 hdmi2.0 and could be extended to work on them by changing the end part 
example (I8:O6) =input 8 to output 6

**Comment by haakonnessjoen** [comment]
Aw.. Seems like #110 is not using LW3 protocol, or else we could have combined this.

Would anyone be able to give me remote access to OPTC and/or a matrix over internet/vpn or anything? While the protocol documentation is quite good in the product manuals. It is also a bit lacking in important places.

I would like to try to connect to more than one type of LW3 compatible product, ant try to fetch the number of inputs/outputs, so that the module automatically can prepare the input fields of our module. So that the OPTC would show 2 inputs and 1 output, etc. But a 16x16 would of course show 16 inputs and 16 routable outputs.

I did however start a lightware-optc module that is basically done now. But I am unsure if I should bother, if we could support all LW3 matrixes, instead of only this one. I also want to play with notification support, so that we can use data from the matrix in our up and coming feedback system.

**Comment by haakonnessjoen** [comment]
This has been created as the module "lightware3". Not commited to master branch yet. It should support most LW3 compatible devices with crosspoint support.

Will be added immediately after 1.1.1 release.
