### ISSUE TITLE
Change time unit in delay (with dropdown maybe :) )

### ISSUE THREAD

**Issue by Fred-DTV** [bitfocus/companion#1466]
**Describe the feature**
A dropdown menu to change the time unit for the delay time ms/s/m/h

Alternativly: have single fields for the different units.

**Usecases**
Would provide a faster and cleaner look for the delay

**Comment by Julusian** [comment]
I'm not sure about this, the delay field already feels like it is taking up too much space.
We should prototype to see how it will look before concluding

**Comment by Julusian** [comment]
#3163 changes the delay field, which I think makes this less necessary.

But upon re-reading this, I am not convinced it is a good idea to do this anyway, the delays within buttons are not designed to be long running, they are intended to be in the scale of seconds. For anything needing a time unit of minutes, delays within a button is not the intended place to do that.
So I am going to close this as we don't intend to support/encourage this flow.

**Comment by dnmeid** [comment]
>  the delays within buttons are not designed to be long running, they are intended to be in the scale of seconds.

The setTimeout() safely can run for minutes and hours if needed. I agree that there are better ways of handling hour long delays but even if it feels strange, for the Companion user the delay in a button may be the best or only way to also realize long delays.
I'd also strongly discourage to use it for hours. I agree that they are meant for seconds but would only mildly discourage to use them for minutes.

While we are now changing this from delay to wait, maybe it would be a good move to change the units from Milliseconds to Seconds (without an option). I always felt that the ms accuracy is only there because we've been to lazy to code a more sophisticated interface to setTimeout() and the average Companion user does not need ms accuracy. Typical delays are either in the range of seconds if you really want to delay something or in the range of 10-50ms if you're abusing the delay to avoid race conditions. The second usecase is now obsolete with the sequential execution mode. What is left is real wait times.
I feel 1.5s more convenient than 1500ms, 120s much more convenient than 120000ms and even 0.01s not worse than 10ms.

**Comment by jswalden** [comment]
> Typical delays are either in the range of seconds if you really want to delay something or in the range of 10-50ms if you're abusing the delay to avoid race conditions. The second usecase is now obsolete with the sequential execution mode.

This is only true if the module in question has actually gone to the trouble of tracking involved operations sufficient to delay exactly until the racing is complete.  Maybe every module _should_ track to that degree, to most correctly model execution.  But I wouldn't fault modules that historically deemed that degree of tracking unduly complicated (especially as sequential execution of this sort only just came into existence).  I know at least the SQ module has some cases where it fires off a command to the mixer but maintains none of the state needed to know when the command has been processed.  I certainly feel no guilt at all about just adding few-millisecond delays to my own uses as "good enough"!
