### ISSUE TITLE
[BUG]: MacOS zip build broken

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#1506]
**Describe the bug**
`yarn dist` produces a file `companion-x.x.x-mac.zip` that contains an invalid app

**To Reproduce**
run `yarn dist` on a Mac

**Expected behavior**
`electron-build` creates `Companion-x.x.x.dmg` in the `electron-output` folder, which it does, and opening that volume and dragging the app to the applications folder results in a working version of companion.
It also creates the file `Companion-x.x.x-mac.zip` in the `electron-output` folder, but uncompressing that archive produces an .app that will not run.

**Desktop (please complete the following information):**

- OS: macOS Catalina (10.15.7)
- Browser: Safari
- Companion Version: Latest build, and back many builds

**Additional context**
This has been broken for a very long time, but isn't critical since the `.dmg` works fine.

**Comment by Julusian** [comment]
Is the zip useful when the dmg works?
The easy option is to disable building of the zip, and avoid the confusion/misleading output

**Comment by MeestorX** [comment]
dmg can be problematic for some people, if they don't want to install to their application folder. (Or so I've heard)

Certainly not worth spending a lot of time on it, but figured if someone understood `electron-build` maybe they'd know what setting needed to be tweaked.

**Comment by Julusian** [comment]
But you can drag the app out of the dmg to a different folder instead of Applications? Slightly less elegant, but as I've always hated the way mac extracts zips this sounds better to me :)

I suspect its going to be something like some symlinks getting messed up when zipping. I have done a quick investigation and I am seeing 2 issues:
1) the binary inside the app is not marked as executable (not confirmed to be an issue, but likely to be)
2) any symlinks inside the app are broken. A documented issue: https://github.com/electron-userland/electron-builder/issues/4299#issuecomment-544997415

**Comment by MeestorX** [comment]
> But you can drag the app out of the dmg to a different folder instead of Applications? Slightly less elegant, but as I've always hated the way mac extracts zips this sounds better to me :)

True, and I don't quite understand why people have issues with .dmgs, but there's still lots of people that freak out when an app isn't signed and notarized, so there's that.

If you want to just turn off the .zip creation, it wouldn't bother me.

**Comment by Julusian** [comment]
I can understand wanting it signed, and I guess notarized, but not the zip vs dmg part..

Yeah ill disable it and close this
