### ISSUE TITLE
Bug: Livecore select screens for global take and Global take commands 

### ISSUE THREAD

**Issue by MrLazerface** [bitfocus/companion#151]
**Describe the bug**
In the Livecore module, the following commands do not appear to work:
-Livecore: Select screens for global take
-Livecore: Take selected screens

**To Reproduce**
-Testing on a nextage 16.
-Both commands do not appear to affect anything in the system. Selecting screens does not show them as enabled in the WebRCS, and the Global take command does not work at all.

**Expected behavior**
-Selecting/de-selecting screens should be shown in the WebRCS
-Global take should take screens to program

**Desktop (please complete the following information):**
 - OS: Win10 64bit
 - Browser: Chrome v67.0.3396.99 (64 bit)
 - Version: 1.1.0-f50028a-win64

**Comment by dnmeid** [comment]
The selection and the global take is not reflected in WebRCS. That's the way AnalogWay implemented the commands in the third party protocol. The selection of the screens in WebRCS is independent from it (same if you use more then one WebRCS). So that is not a bug.
Did the changes of d1d9ebe fix the problems with take for you? Actually I tested all commands and in my opinion it should have been working before and shouldn't work now. I think the command should be 1SPtsl\n instead of SPtsl\n

**Comment by dnmeid** [comment]
I can confirm that both commands have been working. The workflow is:
1. select the screens you want to take. The selection is not reflected in WebRCS and is only valid for third party control.
2. take the selected screens. If you don't make a selection in advance take will have no effect, but the selection is stored until you change it.
