### ISSUE TITLE
[BUG] GUI v2 shows incorrect action value

### ISSUE THREAD

**Issue by maxks** [bitfocus/companion#1514]
In module Allen&Heath SQ there are actions to Mute various channels.
In this action there is a option that shows mute type:

0 => Toggle
1 => On
2 => Off

In GUI v1 I set all mute channels with mute option to Toggle (0), but GUI v2 shows all otions set to On (1) but core works correctly. If with GUI v2 I change the value of mute option, next time I open GUI configurated value is setting correctly both in v1 and v2.

GUI v1
![image](https://user-images.githubusercontent.com/5967320/112151248-4c5d0880-8be1-11eb-9e83-c4cd4804035b.png)

GUI v2
![image](https://user-images.githubusercontent.com/5967320/112151302-5c74e800-8be1-11eb-9c17-44b9cfea5690.png)

**Comment by Julusian** [comment]
If in the new ui you change it back to toggle and refresh the page, does it remember that selection?
I am wondering if this is an issue with `1 === '1'` and `1 == '1'` giving different results

**Comment by maxks** [comment]
Yes, if I change value on new UI it remember that selection and both ui 1 and 2 shows correct choice.

**Comment by Julusian** [comment]
ok yeah my suspicion is the likely cause then

**Comment by Julusian** [comment]
@maxks this isnt as simple as I thought. could you send me an export of a page containing the button both being wokring and broken?

**Comment by maxks** [comment]
Hi @Julusian I exported page from UI v2. Buttons 1.2 and 1.3 were changed in UI v2, other buttons are confugured in UI v1 and all buttons has mute options as "Toggle".
[MacBook-Pro-di-Massimiliano.local_page 1_20210326-0742.companionconfig.zip](https://github.com/bitfocus/companion/files/6209850/MacBook-Pro-di-Massimiliano.local_page.1_20210326-0742.companionconfig.zip)

**Comment by Julusian** [comment]
ok, this is a weird one and I would argue is a bug in the allenheath-sq module.

From your config, this is the actions (with some junk stripped out) on 1.3 and 1.4:
```
"3": [{
    "action": "mute_input",
    "options": {
        "strip": "44",
        "mute": 0
    },
}],
"4": [{
    "action": "mute_input",
    "options": {
        "strip": "46",
        "mute": true
    },
}],
```

That actions has a definition for mute of:
```
{
    type:	'dropdown',
    label:	'Mute',
    id:		'mute',
    default:	0,
    choices:	[
        {label: 'Toggle', id: 0},
        {label: 'On', id: 1},
        {label: 'Off', id: 2}
    ],
}
```

The behaviour is then a compound of in
https://github.com/bitfocus/companion-module-allenheath-sq/blob/main/index.js#L534, `parseInt(true)` gives `NaN` and `NaN` is not greater than 0, so falls into the toggle route.
But in the ui, `1 == true` passes so the dropdown shows the 'incorrect' option. However none of the ui options is technically the correct one. The old ui is only showing the 'correct' thing because none of the options match so it is showing the first.

Potentially I could make the equality check be `1 === true` so that it fails, but I am pretty sure I had to do the looser one because the value can be converted between a number and a string unexpectedly.

So my conclusion here is that your actions are what are wrong, and is likely caused by the module not having done an upgradeScript at some point when the mute option changed from being a checkbox to a dropdown

**Comment by maxks** [comment]
It is possible that your conclusion is correct. In fact, I never created an update script when I changed the behavior of the options.
Sorry for mistake!
