### ISSUE TITLE
Color options for button feedback

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion#1521]
**Describe the feature**
Offer a choice of text color with every background choice

**Usecases**
Many modules make it possible to set the background color for certain conditions.  However, the text color on the button restricts those choices to less than half, lest the text be unreadable.  A choice to change the text color as well as the background would be useful

**Comment by Julusian** [comment]
All of the feedback fields including the colour input are provided and handled by each module. So to improve this would require going through every module and checking each feedback.

This is not something that anyone has the time to do, so it would best for you to open an issue for it on each module where you find this to be an issue, so that the work can be more directed
