### ISSUE TITLE
Toggle Button Function rather than single action

### ISSUE THREAD

**Issue by AlexWHughes** [bitfocus/companion#154]
One of the great thing that the original stream deck software allows you to do is a two-state toggle commands on buttons. It would be really fantastic if we can change the delay command to have an option to wait for a second button press such as a projector shutter toggle where it sends two PJlink values, etc on one button. Obviously with button feedback that I know is being worked on this would be great.

**Comment by dnmeid** [comment]
Toggle functionality is a thing which definitely has to be possible. But although it sounds quite easy at first hand it is hard to implement if you want to do it right in a remote control environment. Anyone who has a universal remote for TV knows the problem of toggle commands. We cannot simply store "button is on" or "button is off" because other controllers might have changed the actual value. E.g. Companion opens the shutter and thinks it is open, guy with remote closes the shutter. Companion still thinks it's open.
That means toggle actually is command in relation of what the actual state of the device is: if shutter is open, then close and if shutter is closed then open.
First there is the feedback-system to be finished to dig into this and maybe such toggle functionality will be possible right away with the feedback-system.

**Comment by willosof** [comment]
Yes! We will have toggle with an action for on and off, and even keypress with on keydown action and keyup-action. Useful for lighting/osc messages etc.

**Comment by AlexWHughes** [comment]
No rush. Thanks guys.

**Comment by SSormunen** [comment]
Also add that both toggle states can have their own image and text ;)

**Comment by willosof** [comment]
Done in feedback branch.
