### ISSUE TITLE
when selecting an action on a button, make searchfield active

### ISSUE THREAD

**Issue by fdebeer** [bitfocus/companion#1549]
here i am again :) just a small and simple feature to make life a bit easier.

**Describe the feature**
make searchfield active when selecting a action on a button.

**Usecases**
when selecting an action for a button and having many instances you can scroll through the list which is a pain...
you can also type what you need which makes it a lot faster and easier. but to do that you have to click in the searchfield first.
it would be nice to be able to start typing in the field right after you select the button without first have to activate the searchfield.

**Comment by Julusian** [comment]
I am not sure if this is a good idea. While it would make it quicker to add new actions, I dont know if the add actions box is the right place to have focus.
When creating a new button it would make more sense to focus on the label field first. 
And why down actions rather than up actions? (Currently this is a stupid question, but once I get around to trying to implement https://github.com/bitfocus/companion/issues/925#issuecomment-731751129 then which action type should be the focused?)

**Comment by fdebeer** [comment]
@ Julusian, i think you misunderstand me. my suggestion has nothing to do with #925 
what i'm suggesting is to give the searchfield focus so you can start typing in the field without clicking in it first. 
this can be done in the key-down, key-up and feedback. 
![key-down](https://user-images.githubusercontent.com/45366426/113708331-60286480-96e1-11eb-9a2f-8fdec35715f1.jpg)

**Comment by Julusian** [comment]
oh right yeah I did misunderstand you a bit.
I didnt realise that box wasnt focused when clicking on the dropdown...

But this is already done in the new ui, and the old one is going to be removed from the 2.2 betas this week, so I dont think there is anything to do here. If you are running a 2.2 beta, try switching to the new ui in the left sidebar

**Comment by fdebeer** [comment]
thanks, using the new ui from now :)
