### ISSUE TITLE
Feature Request - Trigger off feedback

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion#1562]
**Describe the feature**
Be able to create a trigger off not just from a variable, but from feedback from a module

**Usecases**
This would allow the ability to press a button based on the feedback from another module - e.g.
- Mute a source when a media clip has finished playing

**Comment by josephdadams** [comment]
@onfire4g05 possible?

**Comment by onfire4g05** [comment]
Hmm, I've thought it might be a little too complex in the past, but I think I'm not thinking it through enough.

I'll try to look into it this week. It'd definitely be a cool feature to have.

**Comment by Julusian** [comment]
Yeah previously I've thought it song be possible with current architecture, but maybe it is. Mostly because feedbacks return either an empty object, or ab object of the properties to override. If you check got that being empty that would work for most feedbacks, but a few will always register as true.
Listening for feedbacks changing should be pretty simple.
And with the new ui, that should also be pretty easy to reuse the existing feedback editing in the triggers ui.

**Comment by Julusian** [comment]
PR for this #1604

**Comment by Julusian** [comment]
With #1604 now merged this is possible, but it does rely on modules to change their feedback to be compatible. If you find a module you need it for, then please open an issue in the correct repository for it.
You can post a link to the issue here if nothing happens after a couple of weeks, and I can try and find some time to help get them updated
