### ISSUE TITLE
"Set Surface" Action Forward/Backwards does not work 2.2.0 build 3352

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion#1620]
FORWARDS and BACKWARDS for the action _"internal: Set surface with s/n to page"_ does not work in 2.2.0 build 3352. (Setting a specific page number still does work, but not forwards or backwards).

<img width="525" alt="Screen Shot 2021-06-03 at 8 42 09 AM" src="https://user-images.githubusercontent.com/76959770/120648336-82243600-c449-11eb-9847-1f8a45f698f4.png">

**Comment by istnv** [comment]
_Forward_ and _Backward_ use an internal list of pages 'set' since starting companion. 
When companion starts, the list is empty and _Forward_ has no place to go.
Where would you expect _Forward_ to go when there are no pages used yet?
Example:

- Deck is on page 5
- Press Go to page 10 (adds page 10 to list, if the list is empty add page 5 before page 10)
- Press _Backward_  to return to Page 5
- Now press _Forward_ and go back to Page 10

**Comment by davidjoshuaford** [comment]
Ah, thank you! 

Has this function changed recently? If my memory is correct, it used move the surface's page Forward/Backward in relation to the adjacent page number:

(ie, if on page 10, pressing Forward would take you to page 11).

**Comment by istnv** [comment]
> Has this function changed recently?

It was. They were never well defined and _Backward_ didn't always do what you expected.
Start from page 5, go to page 10. If the list was empty, it only added 10, at which point _backward_ did nothing.
Now you can _Go to_ page 50 (for example, camera position/focus/zoom) from page 5 or 10 and then _Backward_ will return you to the correct page.
_Up_ and _Down_ were not added because there are keys for that.

**Comment by davidjoshuaford** [comment]
Cool! I like it. I'd been using the old version to jump through multiple banks of macros etc. Will have to update that. Thanks for the info.
