### ISSUE TITLE
Define or re-order sequence of triggers

### ISSUE THREAD

**Issue by tim-barr** [bitfocus/companion#1636]
This is a requested addition to #1604 

Functionality requested: Execute triggers in a particualr sequence.   This could be:
1) the physical order of triggers, which would require the ability to rearrange them.
2) Add a field for "sequence number" 

**Usecases**
Although an individual test may not care about the sequence of the testing, the sequence of multiple triggers matters and more than one triger may be true.  The last trigger executed essentially has the highest priority.

For example: A trigger is controlling a blink light to function as Tally based on Atem vairables.  It sets it to "off" under certain conditions.  A separate trigger to turn it on for Program would need to run AFTER the  the trigger that turns it off.

**Comment by Julusian** [comment]
One way to force the order would be to add a small delay to the actions being executed, so that they will always happen in the desired order.

I think that we need to be careful about making the list be reorderable, because the list order won't always be followed, depending on the feedbacks used to trigger it.

As an example:
Let say there are two triggers:
1) listening for program on the atem to be 1
2) listening for preview to be 2

You perform a cut operation on the atem which in the same instant, makes both be true.

But internally to companion, that is two feedbacks being invalidated. 
These are executed one at a time, and iterate separate iterations through the triggers to check if they are affected. So no matter the order the user wants, it will be determined by the order the module invalidates the feedbacks.
This isnt be a problem for the atem module anymore, but will affect many others which are unlikely to be updated to avoid this. But it will still be the case if one is a feedback and one is a variable.

Alternatively, there might be time between companion being made aware of them both changing. The atem sends each of preview and program as separate commands over the connection. Depending on various random factors, it is possible for them to be received a few milliseconds apart. 
Again this will apply to many modules that are notified about changes. 

The point being that we cant guarantee execution order, and I think attempting to do it will be misleading and end up with many reported 'bugs' of times when it isnt working.

**Comment by mark-epstein** [comment]
I was going to suggest that I'd like to be able to re-order triggers just for housekeeping.
If I have a list A B D E C and I want to put them in order, with the "clone" option I can get there by cloning and then deleting the original D and E, but it gets unwieldy as the list grows.

**Comment by Julusian** [comment]
Reading through this again, I still don't think we will be able to provide any form of guarantee over execution order, as it is going to be too easily influenced by factors out of our control. So giving users a way to try and influence this order doesnt sound like it will be helpful very often. 

The visual order of the list is also covered by #2035
