### ISSUE TITLE
Request: Hide page selection

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion#164]
Would be great to have the option to hide the page selection on the Streamdeck and having one more column of buttons. - Maybe as an advanced mode, with different Streamdecks so they can hold different buttons.

**Comment by MartijnKraats** [comment]
Or make a Master page button. (second row left button). Clicking on this button will activate the 15 buttons to go to page 1-15 immediately,

**Comment by willosof** [comment]
This is on our todo list:)

**Comment by haakonnessjoen** [comment]
We have this on our todo. But we need to figure out the best way to do this without breaking everyone's config. The problem is that currently, bank 1.5 is on second row on first page. If we add another row; bank 5 would be on the first row. So your whole "page design" would be all messed up.

We have a grand plan of redesigning the entire page/bank system. Where banks reside inside large virtual spaces. I do not think we can implement this "hide page selection" feature, before we have implemented this new system. It would just be double coding.

If anyone have any better solutions to this problem, please come forward :)

**Comment by Keksstar** [comment]
Can be closed. As it´s already working :)
