### ISSUE TITLE
Trigger Question 

### ISSUE THREAD

**Issue by janno1722** [bitfocus/companion#1700]
I want to turn the trigger on and off with a defined key. 
I miss the key mapping for the triggers.

![Screenshot 01](https://user-images.githubusercontent.com/89399094/131215246-181dc51e-834e-47dc-a84a-94957fd9737d.png)
![Screenshot 02](https://user-images.githubusercontent.com/89399094/131215249-4723ecfc-52cf-4aed-89c0-84d96cebcca9.png)

macOS Big Sur Version 11.5.2
Companion Beta Version: 2.2.0-1cc51029-3526

**Comment by janno1722** [comment]
![Screenshot 03](https://user-images.githubusercontent.com/89399094/131215396-3a108525-d3cc-45df-9462-d7ef8c224403.png)
![Screenshot 04](https://user-images.githubusercontent.com/89399094/131215399-62853c09-6589-4fb4-b4b9-3002d0ca52ef.png)

**Comment by josephdadams** [comment]
@onfire4g05

**Comment by onfire4g05** [comment]
I do agree that that was nice to have; however, @Julusian rewrote a bit of the trigger code to support multiple actions vs being mapped to a single button. It can now do a ton more than it was originally able to. The downside is now the review page can't show the button since it could be doing anything a button does.

What might be useful is to have a list of actions a specific trigger does underneath the conditions on the review page; however, that would get cluttered quickly if there's multiple actions. Maybe the page could show the first action and then have `...` to show the rest if there are multiple actions assigned to a trigger?

**Comment by Julusian** [comment]
The button preview had to go away when converting the triggers to run actions directly. Because pressing a button is now a small part of what a trigger can do, and I would discourage doing unless necessary. It is much better to have the actions listed inside the trigger where possible, as it reduces the need to jump around between different areas of the ui when trying to figure out what the trigger does.

Yeah I think it will be difficult to descibe the actions in a nice way. We don't have a way to format an action as a string currently, but something crude could be put together quite easily. eg `internal: Button press and release (Page: 2, Bank: 17)`.
