### ISSUE TITLE
StreamDeck 

### ISSUE THREAD

**Issue by ocintrawets** [bitfocus/companion#1720]
**Describe the feature**
I am currently using a networked PDU by tripp lite. Is it possible to add this as a device to bit focus companion so that we cna control this item via streamdeck 

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by josephdadams** [comment]
This is a very incomplete module request and not in the correct location. Please make your request here: https://github.com/bitfocus/companion-module-requests/issues and include model information and protocol information in order to be able to control it. We should not have to do your homework for you.
