### ISSUE TITLE
[BUG] unauthenticated git error with manual installation on raspberry pi

### ISSUE THREAD

**Issue by urbanvisuals** [bitfocus/companion#1778]
****
**Describe the bug**

When trying to manually install on a Raspberry Pi 4 I get the following git error:  

```
error Command failed.
-Exit code: 128
command: git    
Arguments: ls-remote   --tags    -heads git://github.com/willosof/node-barco-eventmaster
Directory: /root/companion
Output: fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported. Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

I think that line 885 in companion/yarn.lock causes the error. 

`git:github.com/willosof/node-barco-eventmaster#b6c6586ec02b674b9c3051e0bc79b35d04b80748
`
I think the fix is as simple as changing that line to:

`https://github.com/willosof/node-barco-eventmaster#b6c6586ec02b674b9c3051e0bc79b35d04b80748
`

**To Reproduce**

**Expected behavior**

**Screenshots**

![Messages Image(3809552792)](https://user-images.githubusercontent.com/2680423/139953747-0c06a335-2854-4a2b-8bf4-e31d99663c4c.jpeg)

**Desktop (please complete the following information):**

- Companion Version [e.g. 2.0]

**Additional context**

**Comment by McHauge** [comment]
From what i can see this is just the normal git not being configured on the device, and that would be needed in order to get that part.

This only really became a thing after github changed their authentication requirements.

Personally I don't see this as a companion problem, but could be seen as a missing step in the documentation.

Might be wrong though, but looks a lot like an error I have gotten when setting up new environments and cloning from GitHub

**Comment by Julusian** [comment]
@McHauge from skimming the linked article, I think this was from a scheduled brownout https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective

If the dependency is defined differently (such as like we do for the module github dependencies in the package.json in this repo), then it will not try and use the 'git' protocol and will work fine

**Comment by Julusian** [comment]
I have changed the import so that this should no longer be a problem
