### ISSUE TITLE
[BUG] Have to use Release 2x after using Press.

### ISSUE THREAD

**Issue by KzBoy** [bitfocus/companion#1809]
**Describe the bug**
Using the 'Press' command on another button will cause the target button to ignore the first 'Release' command ('Press and Release', and directly triggering the button work fine).

**To Reproduce**
1. Add three buttons: __Target__ (Latching), __Press__, & __Release__.
2. Add a 'Press' command targeting the __Target__ button.
3. Add a 'Release' command targeting the __Release__ button.
4. Activate the __Press__ button.
5. Activate the __Release__ button.
6. Activate the __Release__ button.

**Expected behavior**
That the latched __Target__ button will release the first time __Release__ is pressed.

Instead it takes 2x presses. You can also get the expected behavior by sending 2x __Press__ commands followed by a __Release__ it only happens from a __Press__ > __Release__.
Note: __Target__ must be Latching style.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Companion Version: 2.2.0

**Comment by istnv** [comment]
This is a byproduct of the way the physical button works. A latching button is specifically programmed to ignore the next release message, otherwise, letting go would immediately 'unpush' the button. The press/release message processing does not indicate where the message came from (physical button, internal press, http message).
To achieve what you expect, change the 'Press' button action to 'Internal: Press and Release' to reset the 'up' filter. Another way is to put 2 'Release' actions on the Release button.
Latching buttons also prevent 2 presses or releases in a row from re-running the actions.

**Comment by KzBoy** [comment]
That makes sense.

I figured it must have something to do with the way latching mode works. I'll use press & release for now I suppose.

Would be nice to come up with a 'solution' to this in the next version as I think it would cause inconsistent results for people that would drive people crazy. 😅

**Comment by Julusian** [comment]
This wont change in the stable release of 2.2, but will change with #1630 in 2.3

**Comment by Julusian** [comment]
Closing this, as it is 'as designed' in 2.2 and earlier, and there are already plans to improve it in 2.3
