### ISSUE TITLE
From variables create a Preset Buttons or Trigger

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#1831]
From the Variables page. Have an option to create a button or Trigger from that page

**Comment by estilles** [comment]
@hadphild 
Not exactly sure what you mean. Can you please provide more details?

**Comment by hadphild** [comment]
On the Variables page, have a Draggable Button to the interface with the variable as the name. Also in the Variables page have a link to create a trigger from there as well and take you creating a trigger from there.

**Comment by estilles** [comment]
> On the Variables page, have a Draggable Button to the interface with the variable as the name. Also in the Variables page have a link to create a trigger from there as well and take you creating a trigger from there.

Gotcha! I can see how that could be useful.

**Comment by krocheck** [comment]
@hadphild I see what you're asking for, but that's why the variables all have the "copy" button.  Is that not sufficient?

**Comment by hadphild** [comment]
@krocheck its more a usability thing. 
Preset button are really useful for speed. Variables could being a drag able buttons like the presets. 

Or the variables can just presets as well.

**Comment by krocheck** [comment]
I'll bite.  If you drop on an existing button is it:

A. Just replacing the text itself (no style changes)
B. Replacing the text and some style properties
C. Resetting the button with empty actions/feedbacks

For consistency with presets I think it would have to be C, but is that truly useful then compared to a developer properly implementing presets?  And I'll own up that even I have some modules that I skipped doing presets that I should have.

**Comment by Julusian** [comment]
I think there are more options than what you suggested:
D) Append to the end of the button text
E) Replace the existing variable in the text (eg, if it was `$(something)dB` it will become `$(newThing)dB`)
F) Add the 'internal: check variable value' feedback to the button

I think that a better thing to do would be to implement a better variable picker in the dropdowns and text input fields.
I dont know how it should look yet, but if we do that then it will be much easier to find the variable you are looking for when defining a trigger/button. It may not help with 'speed of defining buttons', but as krocheck suggests, there are multiple ways it could work and no matter which we do someone will be annoyed by it

**Comment by krocheck** [comment]
E) Is complicated if there's multiple or nested variables inline.

There could be a "Drag & Drop Behavior" (or something) dropdown in the variable tab to cover this (except E) if we went with previews.  But just adding the variable tab and copy button like we did was supposed to alleviate much of this because in the old UI they were buried and you have to switch away from what you were doing to even browse them.

Is there any way we can remember last cursor position and add an 'Insert' button next to the copy button?

**Comment by hadphild** [comment]
All are great ideas glad I have started a good discussion.

**Comment by Julusian** [comment]
It has been a couple of years since this was opened and last had a comment.
As far as I can see, there is no clear proposal on what exactly should happen, so this is stuck waiting for that.

If someone wants to argue for a particular behaviour that they think is sensible, then this can be reopened, but I am closing it for now as nothing is going to happen until that decision is reached and there hasnt been any progress towards that
