### ISSUE TITLE
I18N: Do we want internationalization support? (translate user interface)

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion#195]
## Do we want i18n support?

Please +1 this post if you feel that this is something we should have. Or even -1 if you think that is not something we should use our time on.

Use the smiley button just above this post to choose. 

The translation process would of course be a community effort. So we won't magically have support for all the languages in the world. But maybe you want to contribute yourself? No development experience needed.

**Comment by dnmeid** [comment]
I think we need support for non latin characters in textfields (e.g. for buttons). I have plenty of them already but no Cyrillic or Greece or Katagana or...
Furthermore I think we should have a getting started guide in several languages, like spanish, french...
But for the GUI I think we don't need internationalisation. I once did the whole i18n stuff for another open source project, which really needed it because of language diversity in New Zealand, I wouldn't say it was a waste of time but there have been two people writing a translation and after that the translations haven't been updated along with the development. This lead to fancy language mixtures depending of the language preferences of the browser which many users even don't know about. Generally it was a fail.

**Comment by rodrigocaravaca** [comment]
Something i can help with!. 
I could translate to Spanish texts and localize anything that´s needed. Although Dnmeid maybe has a point about leaving the GUI in english.

**Comment by kutuz00** [comment]
Can help with Cyrillic Support. Russian and Ukrainian
