### ISSUE TITLE
Macro Library

### ISSUE THREAD

**Issue by samuelbailey123** [bitfocus/companion#1954]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I think it would be really cool if we had some sort of library of things to call inside of a button. 

For example, 
A Macro that does 
Macro name FOO
1. Action
2. Another Action 

Then inside of a button I could call FOO and add on to it etc..

### Usecases

This is similar to in code whenever you are using an algorithm of actions repeatedly we create a function. This would be like that. A lot of projects repeat commands and it would be nice to just make them into callable macros. If something like this already exists I'd love to learn how to use it. Thanks!

**Comment by niklasberlin** [comment]
would be nice addition to make stuff like this more clear for other users of my setup (a plus would be some conditions inside these macros like: if variable "x" is bigger than "y" do "z" otherwise do "a")

my current workaround is to have one page of helper buttons and then I trigger these buttons from Buttons on my actual working pages via the "Button press and release" action

**Comment by amcchord** [comment]
Worked with the engineers to get some features added that actually have that variable compare.. But yeah thats just the beginning. Branching inside macros would be awesome.

**Comment by samuelbailey123** [comment]
Any update on this idea?
