### ISSUE TITLE
Auto-size font

### ISSUE THREAD

**Issue by waltimo** [bitfocus/companion#199]
**Describe the feature**
Button text autosizing option. In addition to setting fixed size.

**Is this platform dependent (windows, mac, ..)?**
Same for all platforms

**Usecases**
When entering new text it would use default size option from user preferences. If autosize is used it would use biggest font size. When entered text goes over buttons pixel area it would select smaller font. Maybe auto wrapping text would be needed also.

When editing text afterwards by adding characters you would not be required to change font size manually. 

Thanks!

**Comment by dnmeid** [comment]
Actually I thought about that feature too when implementing the font sizes. But at that time I decided against it because of K.I.S.S.
Auto sizing and auto wrapping together can lead to confusing results for the user, although there is no technical problem with both.
The drawAlignedText function already gives back wether the text fits, so it shouldn't be a big problem to use it for auto sizing.

**Comment by dnmeid** [comment]
This now has been implemented with 3ba3449367b98d9f80c9b5ed5b9966875e7c4733
