### ISSUE TITLE
[BUG] Raspberry Pi: Can't shutdown via shell command

### ISSUE THREAD

**Issue by JPJayPee** [bitfocus/companion#2001]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On a previous setup I was able to setup buttons that would shutdown and reboot the companion pi.
For reboot it was as easy as setting up a latch button with `sudo shutdown -r 1` on press and `sudo shutdown -c` on unlatch. That way accidental presses could be reverted. Same for shutdown with `sudo shutdown -h 1`
With the latest 2.2.0 image this is not possible anymore. The companion log will present an error message `instance(internal): Shell command failed. Guru meditation: {"killed":false,"code":1,"signal":null,"cmd":"sudo shutdown -c"}`

Looking through closed issues gave a couple of options but none were successful. I tried `sh -c "$$"`; `/sbin/..`; bash and python scripts

### Steps To Reproduce

1. Create a new button
2. Add button down action `internal: Run shell path (local)`
3. Enter `sudo shutdown -r now` as otpion
4. Test action
5. Check the logs for the error message

### Environment (please complete the following information)

```markdown
- Raspberry Pi 4B
- BF companion 2.2.0 
- Based on latest image from 2022-03-30
```

**Comment by istnv** [comment]
The command shell does not usually have all search paths defined.
So you need the full path to the commands, typically:
`/usr/bin/sudo` and `/sbin/shutdown`

**Comment by rmmcdr** [comment]
Thanks! (I have the same problem)
I tried `/usr/bin/sudo /sbin/reboot` via shell command and I still have an error `Shell command failed. Guru meditation: {"killed":false,"code":1,"signal":null,"cmd":"/usr/bin/sudo /sbin/reboot"}`
It works via ssh command and with the previous version (with the 2021-07-25 version I can use `sudo reboot` even after an `sudo companion-update`)

**Comment by Julusian** [comment]
I think what is happening here is that in the new image, companion is running as a user which doesnt have passwordless sudo enabled.
This is done because its a bit of a privilege escalation issue, anyone with access to the pi over the network can execute a shell command through companion, and as there used to be passwordless sudo they can easily get into a root shell

The 2022-03-30 image is rather different to previous ones, so small differences like this are not unexpected

A solution to this would be to wrap the command up in a shell script (making sure that it is in a directory that the companion user has access to), and doing something like `sudo chown root:root my_shutdown_script.sh` and `sudo chmod 4755 my_shutdown_script.sh`. I havent tested it, but it should work. The idea is to make the script be owned by root and setting the suid bit to make it always be executed as root, even when another user tries to execute it
The contents of the file should be something like
```
#!/bin/sh
reboot
```

I shall look at whether companion-pi can be setup for passwordless sudo for just the shutdown and reboot commands, or provide the required scripts to help with this

**Comment by Julusian** [comment]
> suid .sh scripts are worse security-wise than password-less sudo for gaining a root shell.

Sure, if not permissioned properly, but if they are set to only writable by root then are they?
I dont think I've ever set the suid flag myself on anything, so this is not an area I have much experience in..

**Comment by rmmcdr** [comment]
Thanks a lot for the explanation! I've just tried the "visudo method" and it works great 👍

**Comment by istnv** [comment]
@Julusian 
Unfortunately, it is intended to be awkward. I have seen this method used before from a script:
`"ALL ALL=NOPASSWD: /sbin/reboot,/sbin/shutdown,/sbin/poweroff" | (sudo su -c 'EDITOR="tee" visudo -f /etc/sudoers.d/reboot')`
The Companion-Pi image can be pre-loaded.

**Comment by Julusian** [comment]
The challenge is how to do this to fix up existing installations from the 2022-03-30 image, but I didnt know it could be a dedicated file in a folder like that. That makes it really easy to do, the updater is already doing a similar thing for the udev rules, and update scripting

**Comment by Julusian** [comment]
@istnv that said, the update layer made that super easy to do https://github.com/bitfocus/companion-pi/commit/7df57e4dd497e3a165b4b28b8fd80fd180d20871

For anyone reading with this issue on the 2022-03-30 image, do a `sudo companion-update` and it will work

**Comment by JPJayPee** [comment]
Great thanks! The shutdown commands now work as before. 
With the 2022-03-30 image and a companion update you can just use e.g. `sudo shutdown -h 1` to handle the pi's power state.
