### ISSUE TITLE
Expose feedbacks as variables automatically

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion#2016]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Currently, what is exposed as a variable is dependent on coding by module developers.  Particularly for stale modules, in the sense that they continue to work well but don't have any devs actively involved in further working on them, we are unable to utilize the power of companion with regards to newer features related to variables.  There would be tremendous value in system-wide creation of variables for every module to provide all of their feedbacks as variables automatically and without additional programming from module developers.  Given that companion can see all of this information already, beyond naming conventions to this end, I would think it would be fairly straightforward to implement this.

### Usecases

In particular, I would like to trigger an action if my epiphan encoder were recording and/or streaming.  There is a feedback in place to change button display properties, but there are no variables exposed that would allow me to then run a trigger off of the same data.

**Comment by Julusian** [comment]
This is asking for a similar thing as https://github.com/bitfocus/companion/issues/2016

The problem with this is that those feedbacks which arent available to be used for triggers are written in a way which is incompatible. When they are 'true' they return something like `{ bgcolor: 255, color: 0 }`. And when they are not 'true' that is typically `{}`.

Basically they are written to provide companion with the style information they wish to override. As such, it is difficult for us to know how to interpret the value as a boolean. When false it may return `{ bgcolor: 0 }` or when true it could be `{ text: 'abc' }`. Or when false it could even be `{ text: 'abc' }`

Additionally, while the color inputs it prompts you with are often called `bg` and `fg`, that is not always the case. 

So while we could do something to make those feedbacks usable for triggers, we could at most handle 90% of the feedbacks. And I expect that 10% of those that we think will work will in fact not work, and will be a confusing mess.

I know you are asking for variables to be generated, but it sounds like what you want could be achieved with updated feedbacks. All I said above applies to us trying to generate variables too, plus the problem that some modules only load data from a device when it is used by a feedback. I know the yamaha-rcp module does this, as it has many thousands of possible values. If we were to create variables for every feedback combination, that would be a lot of data for companion to process. Additionally, various modules have text fields in feedbacks, which we wouldnt be able to handle so those would have to be ignored. I feel like its probably closer to 50% of the feedbacks that could have variables generated. And due to the performance impact of this and likelyhood to duplicate aleady created variables, it would probably need to be opt-in per module at which point the modules may as well be fixed a bit.

The proper solution is for the modules to be updated to convert any relevant feedbacks to be 'boolean' feedbacks. There is a wiki page on how to do this, and is a pretty straightforward process. In the case where the module looks unmaintained, then you could try asking in slack if someone is able to do it

I do have plans to look into making modules simpler by prefering variables over feedbacks, but some other work is needed in companion for that which is many months away from being worked on

**Comment by jsnyder886** [comment]
10-4, thanks for the information.  Here I was hoping it was just a simple routine to whip it out.  Oh well, thanks again!

**Comment by krocheck** [comment]
If there's something specific you need and the feedback is supported in triggers, you could set a custom variable with specific text.
