### ISSUE TITLE
Module Request: Analog Way Eikos EKS500 (not Eikos2)

### ISSUE THREAD

**Issue by themusicnerd** [bitfocus/companion#202]
Hi again from Australia,

I would like to make a module request for the Analog Way Eikos EKS500 (not Eikos2).

The TCP Control protocol is documented here:
http://www.analogway.com/files/uploads/produit/download/en/eks500_programmer's-guide-v4.20.pdf

I am happy to try and learn how to program the modules myself if that can be of any assistance?
Is there somewhere where I can read how to program and install custom modules?

Kindest Regards,
Adrian

**Comment by dnmeid** [comment]
Hello Adrian, for sure you can learn how to program a module. Please visit DEVELOPER.md and read the needed information there. The file assumes one is on OSX since all the core developers are using OSX for development (the code will be cross platform).
If you want to code a module for EKS500 you can use e.g. the files from the Midra module as a starting point. The Analog Way protocols are all quite similar, so you only have to change some commands and parameters. Please don't clone the Midra Repository for that, this would clone all the file history too. Make a new Repository like explained in DEVELOPER.md and then add the files manually to the Repo.
You will need knowledge of javascript (the programming language of Companion) and git (the version control system we use). Both are well documented in the web.
And you can get further help in our slack group.

Dorian

**Comment by dnmeid** [comment]
The module is there. Adrian knows, he did it.
