### ISSUE TITLE
[BUG] Companion locks up after 15 minutes

### ISSUE THREAD

**Issue by thec47** [bitfocus/companion#2022]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using the latest 2.2 of Companion with a 2019 Intel MacBook Pro. It is configured to work with the StreamDeck and ATEM Mini Pro. 

I am able to get everything up an running properly but after about 15-20 the connection drops and I am forced to unplug and plug in the ATEM Mini Pro to get it to connect again (which happens automatically and I get the "OK" again). 

I have tried to resolve this but it keeps dropping out. My internet is still intact and can be used otherwise but the StreamDeck no longer communicates with Companion). Nether does the emulator. It says "Reconnecting" but never does until I unplug and plug the ATEM back in.

I have searched for any clues and have come up short.

Thanks for any help in advance!

### Environment (please complete the following information)

```markdown
- OS: 12.3.1
- Browser: Safari and Chrome (same issue in both)
- Companion Version: Latest build of 2.2
```

**Comment by thec47** [comment]
Thanks for the reply. I'm not sure it's the ATEM as it works perfectly and then suddely it just drops out. Once it changes from "OK" to Reconnecting then the Buttons Tab also doesn't work. Just trying to figure out why the connection drops even though the network it up and funtional for everything else. Hard wired via ethernet, not wifi.

**Comment by phwecker** [comment]
we had a similar issue, which was caused by a competing Atem control software session on the network trying to connect to the atem from the same box. a "reconnecting" status we could solve by 

-) ensuring there is no competing atem control software running on the same box
-) disable/enable the module in the admin UI --> then it did successfully reconnect

it is our observation that the atem module seems to be a bit picky when in reconnect state; possibly there is some issue in the retry logic of the connect.

**Comment by Julusian** [comment]
With the new isolation of modules in 3.0, issues like this should no longer happen. 
Please open a new issue if this does still happen
