### ISSUE TITLE
Buttons don't display arabic or hebrew letters

### ISSUE THREAD

**Issue by mbaklor** [bitfocus/companion#2064]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to set up a Companion setup for someone who doesn't do well with english, and per the ["Text input"](https://github.com/bitfocus/companion/wiki/Text-input) wiki page the buttons should support UTF-16, however when I try to add the text to the buttons I get blank space where the arabic or hebrew text should be.

![image](https://user-images.githubusercontent.com/78748463/177354738-b91ad166-37e9-45ca-b775-16d126ffc287.png)

I'm running the latest build on windows 10.

### Steps To Reproduce

add any arabic or hebrew text to any button text

### Expected Behavior

Expect the button to show the text as inputed, considering it's well within the scope of UTF-16

### Environment (please complete the following information)

```markdown
- OS: windows 10
- Browser: firefox 102.0
- Companion Version: 2.2.2 (2.2.2+4454-v2-2.2-be663609)
```

**Comment by Julusian** [comment]
The character set available for the 7pt font is very limited as the characters have to be manually converted. But they should work in other sizes.
#1775 #1316 #910

We will happily accept a pr to add the characters

**Comment by Julusian** [comment]
Oh yeah, it doesnt work for any font size. I dont know what those larger sizes was generated from, that was done 4 years ago and I cant find the pngs used. @dnmeid it looks like you added most of the sizes, its a long shot but any ideas?

The js part of this is definitely generated from pngs, so if you can create pngs for each of the characters for each font size 7px, 14px, 18px, 24px, 30px, 44px. I think the widths are flexible, but Im not 100% sure. 
I vaguely remember someone saying that the current font is based on Arial, so please try to keep to that rough style. I think that the 14px and larger were generated from a real font, so you can do the same, I dont know how best to do that. 
The pngs should be solid black on transparent, you can look at the 7px files in https://github.com/bitfocus/companion/tree/master/font as a reference, and naming them with their character codes would be ideal too.

Once you have those send them over, and I can figure out how to get them imported. Feel free to do one character as a test so we can check it is correct before doing the rest.

**Comment by dnmeid** [comment]
> @dnmeid it looks like you added most of the sizes, its a long shot but any ideas?

Yes, I made all the characters from PNGs. First made all the PNGs and then converted them to the the compressed bitmap font object.
Technically it wouldn't be a problem to also include greek, hebrew, arabic, kyrillic, chinese, japanese, korean, thai and so on.
But that would generate a huge amount of data, increasing the size of companion and slowing load times.
Also by the time of writing that stuff it already has been obvious that bitmap fonts can't be the way for the future. It has been a makeshift ever since. As you mentioned there is no anti-aliasing to enhance compression and to make drawing easier. We always chickened out of doing the big rewrite to use a vector based system. That is nothing you can implement with vanilla javascript and use of compiled tools is a pain when you want to maintain multi platform compatibility.

**Comment by dnmeid** [comment]
Arabic and hebrew coming soon (and some others as well)
<img width="1060" alt="image" src="https://github.com/bitfocus/companion/assets/8548888/978c28d1-7cff-4b8b-acb3-38e75cb60d14">

**Comment by Julusian** [comment]
This is possible in 3.2 (current beta builds)
