### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion#210]
Just an quick question: It´s pretty obvious that the BMD ATEM Control is reverseengineerd cause Companion doesn´t use the BMD API....

Is this approved by Blackmagic or do we get in trouble when using the Software?

**Comment by haakonnessjoen** [comment]
Reverse engineering is not illegal where it was reverse engineered or in the country where Companion comes from. Skaarhoj products have existed for many years, and have grown "large" on reverse engineered products used by big television studios all over the world, and has never had any trouble with anyone as far as I know. Blackmagic loves that people use their products, and delivers SDK for the ATEM free of charge and without any NDA. So as far as I can tell. They would not have any means for starting any lawsuit with the creators or users of Companion. Nor would they be able to win, as far as I know.

The ATEM is a hardware product you buy and own. If you use it in other ways than it was meant to, that is up to you, not the creator of the product. They don't continue to own the product.

**Comment by Keksstar** [comment]
Blackmagic EULA.... discuss….:

6.  The Software is owned by Blackmagic Design or its suppliers. Title, ownership rights, and intellectual property rights in and to the Software shall remain in Blackmagic Design and/or its suppliers. You agree to abide by the copyright law and all other applicable laws of the Australia, United States and other applicable jurisdictions. You acknowledge that the Software in source code form remains a confidential trade secret of Blackmagic Design and/or its suppliers. You may not, permit unlicensed persons to use your copy of the Software, modify, translate, reverse engineer, decompile, disassemble, or create derivative works based on the Software, copy the Software, rent or lease, rights to the Software, or remove any proprietary notices or labels on the Software.

**Comment by haakonnessjoen** [comment]
We have never reverse engineered the software, nor used any of the softwares source code. That point is not applicable.

**Comment by haakonnessjoen** [comment]
I will reference Skaarhoj and say that BMD do not seem to have an aggressive handling of their so called IP of the UDP protocol. So I do not think that anyone would ever get any problems with using companion. Skaarhoj has no special deal with BMD, and BMD knows well about them without taking action. We are a lot younger project, and smaller company. So in worst case scenario, if they contact us, we would simply remove the Atem support, in compliance with BMD, and inform users why it was removed in that case. But this being open source, anyone would be able to re-insert the module at any time.

I will close this issue, since it is not an issue before it happens, and if or when it does. I have no reason to believe that they are suddenly aggressive enough to take action against anyone, before giving a fair warning. And as far as I know, we or the users don't break any of the EULA paragraphs either.
