### ISSUE TITLE
[BUG] Dropdown partially broken

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#2137]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The dropdown as part of action options seems partially broken to me.
What works is the normal dropdown with a single selection and the pill box with multiple selections.
But if you use the multiple: true option and select only one value, the value is returned as a string, not as an array. Previously it has been returned as an array with only one element.
Also the tag functionality doesn't work for me, I can't add options on the fly.

Dorian

**Comment by Julusian** [comment]
> But if you use the multiple: true option and select only one value, the value is returned as a string, not as an array. 

Strange, from a skim of the code it looks like we are making sure to propogate it as an array when appropriate. Ive not encountered any issues with this either in my own modules which use this. 
If the default value is not an array, then that will get passed back unmodified. Could that be what is happening?

> Also the tag functionality doesn't work for me, I can't add options on the fly.

I assume you mean setting `tags: true`? That is not something I expected to hear about again. When doing the ui rewrite to react I couldnt find a module that was making use of it, so it got skipped.
Since then I did add a `allowCustom: true` property that looks like it might be basically the same thing. I don't think Ive tried it in combination with `multiple: true`, so it could not work correctly.

**Comment by dnmeid** [comment]
The default value indeed was the problem of the string return type.
Regarding allowCustom, it works also with multiple but it doesn't reflect the regex checking.
I'll change the development wiki to the new property name.

**Comment by Julusian** [comment]
Ah, `maxSelection` looks to have been broken in the ui rewrite. And accidentally got renamed to `maximumSelectionLength`.

`grep` doesn't show any modules using this property, so ive renamed it back to `maxSelection`


It looks like the only thing left is fixing allowCustom and regex when used with `multiple: true`

**Comment by Julusian** [comment]
The regex was being used as he visual hint giving a red outline, rather than blocking adding of elements, as that is all that was needed when using this with multiple=false in a device config.

The regex will now also be checked too, and it wont be possible to use/add the custom value unless it matches the regex https://github.com/bitfocus/companion/commit/eed274ffafd5642c637342089ce54d5ce6d60a44
