### ISSUE TITLE
allow modules to create custom variables and set/get their values

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2161]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

`setVariableDefinitions()` and `getVariable()` `setVariable()` should be expanded to work with custom variables.

### Usecases

Allow modules to create/delete custom variables on the fly and get/set values for them.

**Comment by Julusian** [comment]
In v3, we are considering letting modules be able to set custom-variables (method is https://bitfocus.github.io/companion-module-base/classes/InstanceBase.html#setCustomVariableValue, marked as experimental while we decide if this is a good idea).
It is intended that this should only be used to store the 'result' of an action. For example, the internal 'execute shell command' does this with the output of the shell command, and generic-http does it to store the response of the http request.
Modules are intentionally not able to discover what custom-variables exist, they can only do so using the `custom_variable` option field type, and letting the user pick the variable to be used.

But I don't think modules should be allowed to create them. The idea behind custom-variables was to give users variables that they could create and store values in. Why should a module be creating a custom variable instead of a module variable?

**Comment by MeestorX** [comment]
The use-case in my module is to allow users to decide for themselves what variables they need and have their values changed by the device.
So, like module-created variables, they get their value from the device, but like custom variables, the user decides which ones they want.
So, creation of the variables isn't critical, the user can do that (as they do now), but the setting of values is critical.
Currently, the user decides which custom variable to set by using the syntax of `@(internal:custom_MyVar1)` (where MyVar1 is a custom variable) in the value field of a feedback. I don't really like this method, as it feels like a misuse of feedback, but there needs to be a way for the user to select which value from the device will fill their variable.
Personally, I think that any device that potentially has hundreds of (module) variables would benefit from this method, as the user can decide for themselves what variables they need, with no predetermined limitations.

**Comment by MeestorX** [comment]
I've made my own solution for this, as long as setCustomVariableValue doesn't go away, we're good. :-)

**Comment by cameocreative2019** [comment]
Is this here to stay? I am planning to send a few custom variables to a webserver and would rather avoid polling the http api. I will create a custom module to do this over websockets, but it will rely on setCustomVariableValue
