### ISSUE TITLE
[BUG] Device ID in action info not set for non hardware triggered actions

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#2180]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The second parameter when calling an action function is an info object, which contains the deviceid, page and bank from where the action has been triggered. When using the emulator the deviceid is correctly set to emulator. For web buttons or when hot pressing an action at the admin gui the deviceid is undefined. Should be something meaningful, ideally a unique identifier per client.
When an action is run from triggers the whole info is null. Should be at least set to `{deviceid: 'trigger'}`

### Environment (please complete the following information)

```markdown
- OS: macOS
- Browser: Firefox
- Companion Version: 2.4.0+4773-beta-3c990f3d
```

**Comment by krocheck** [comment]
This is partially addressed in v3.0.  In the case of the trigger, the device id indicated is the trigger's control ID: `{deviceid: 'controlId'}`  in the form `"trigger:UUID"`.  See [here](https://github.com/bitfocus/companion/blob/6976308b9dd7b8a19d3ccff2967adeefd68b38cc/lib/Resources/Util.js#L236) and [here](https://github.com/bitfocus/companion/blob/6976308b9dd7b8a19d3ccff2967adeefd68b38cc/lib/Controls/ControlTypes/Triggers/Trigger.js#L198).

I believe web buttons will still show an `deviceId` as undefined.  @Julusian seems like [here ](https://github.com/bitfocus/companion/blob/6976308b9dd7b8a19d3ccff2967adeefd68b38cc/lib/Controls/Controller.js#L339) we could do a 
```
let deviceId = `socket:${client.id}`
```
and pass it along in the `pressControl` call; and so the same for `hot-rotate`.

**Comment by dnmeid** [comment]
With so many different types of devices, maybe it is a good idea to have the device-type and device-id split in two properties like `{devicetype: 'streamdeck-xl', deviceid: 'sF4gw1Fr', page: 4, bank: 2}` or `{devicetype: 'trigger', deviceid: 'sF4gw1Fr'}`

**Comment by Julusian** [comment]
I have given hot press a deviceId in #2171, as that is necessary for the test buttons to behave correctly. But it doesn't have a good value currently.

> With so many different types of devices, maybe it is a good idea to have the device-type and device-id split in two properties like {devicetype: 'streamdeck-xl', deviceid: 'sF4gw1Fr', page: 4, bank: 2} or {devicetype: 'trigger', deviceid: 'sF4gw1Fr'}

What is the usecase for this? I currently have deviceId marked as deprecated for modules in 3.0, with the intention of removing it in 3.0/3.1 unless there is a justifaction for keeping it.  
I can't see any module using it other than internal/bitfocus-companion.

**Comment by dnmeid** [comment]
> What is the usecase for this?
I currently use this properties to identify the button which has been used to fire the action. In my case I have two actions working together, one for the press actions and one for the release actions. It is kind of a modifier key. So I need to somehow track wether press and release come from the same button.
For the usecase I'm doing right now I can get along with only page and bank, but only because it is very unlikely that a user opens the same page on two devices and uses the same button at the same time on two different devices. But the moment I think about multi user operation it might break. E.g. if I put a small streamdeck at a lectern and have a XL at FOH. Speaker presses button -> he does so for both devices, Operator presses the same button -> maybe wrong effect because button is already pressed on different device, Speaker releases button -> he does release for both devices.

**Comment by Julusian** [comment]
Thats an interesting use case, and I think conflicts/interacts with some planned/proposed changes in some other interesting ways too.

Im personally not a fan of modules doing shift layer/modifier key things, and would rather that builtin functionality was made to achieve the same, but I can appreciate that isnt always possible. So this might be enough justification to keep the deviceId property. It really doesn't add any complexity to keep it.

But with the page and bank properties being dropped too, will this modifier be possible with the same behaviour?  
These are being removed because a numeric bank is going to be really hard to work with once the grid size is configurable, or is not tied to being a uniform grid. And page because a numeric page is going to be confusing once we refer to pages internally by a uuid, and allow adding/removing/reordering them.  
`controlId` is kindof a replacement for these, but doesnt say where the button is, at some point it will be possible for the same controlId to be on two banks/pages simultaneously.
Some location identifiers could well be added in a different form, if they are useful information. 

Additionally, the behaviour when two surfaces press the same button is a little weird currently. We aren't tracking individual presses really, so once one surface releases the button it is shown as released, but we will fire the actions for each press/release separately. Which is needed so that buttons don't get stuck if a surface never fires the release.
Also in 2.x we arent guaranteeing that a release will fire if it was pressed in multiple places. I have often seen (through my encoder hacks) that firing a release for a button which isnt pressed can be ignored. I never did figure out exactly why, I click it once to the right to trigger a press first which resolves it, but I suspect this is the logic which is intended to reject releases if the page changed while the button was pressed. I don't know if this will affect you or not.

I've been wanting to make a change so that there is a shared 'pressed' state, and we only run the actions when the state changes (pressed when the first person presses, and release once everyone has released it), but had to remove that as it broke how I was doing encoders.  
If I do reintroduce this, that sounds like it will be a problem for your plan with multiple operators. It also makes the deviceId property a bit weird as the actions wont be called for all deviceIds that pressed/released the button.

**Comment by dnmeid** [comment]
For my actual usecase it would perfectly enough if I can clearly compare if two actions have been triggered from the same button or not. If there is a `controlID` unique to each control, that would be sufficient.
For other usecases I can imagine it would be good to know if two actions have been triggered at the same device, but actual no need to know where the button is on the device.
I also can imagine that some actions may want to work different depending on what type the control is, e.g. do some different things on a foot switch or a LCD button or a rotary. Again no need for a location information of the control.
I also can imagine very seldom cases where it may be good to know the location of a press on a surface, but I think it is enough if this is implementable without beeing implemented from start.

**Comment by Julusian** [comment]
All the hot-press calls now have some deviceId value supplied. It may not be the best value, but its something. 
Triggers are using their controlId as a value.
This means that in all cases there should now be a value
