### ISSUE TITLE
[BUG] Button Latch/Toggle is missing in v3 beta

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2243]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Latch/Toggle function is missing for buttons.

### Steps To Reproduce

Select a button, the option is missing.

### Expected Behavior

The Latch/Toggle options should visible

### Environment (please complete the following information)

```markdown
- OS: macOS 13.1
- Browser: Safari 16.2
- Companion Version: companion-mac-x64-3.0.0+5409-beta-e0a1d7a0
```

**Comment by Julusian** [comment]
As documented in the changelog, this is intentional. The new steps on buttons can do what was possible with latching and a lot more https://github.com/bitfocus/companion/blob/beta/CHANGELOG.md?plain=1#L20

**Comment by sstaub** [comment]
It is not a good idea, because latch/toggle works very different.
- I'm missing the yellow border which is a very good indicator for that functions.
- The step function have many unexpected behaviors when initializing.

**Comment by Julusian** [comment]
True you can't get the same border behaviour currently, but other style changes are possible to be defined via feedbacks.

What unexpected behaviours? As far as I remember, adding a second step makes it work the same. But with the bonus of being able to define up actions as well as down actions, and generally do a lot more.

We won't be bringing back the latch checkbox, as its behaviour will be really confusing when combined with steps.
But I am open to hearing what could be done to make the steps functionality better.

**Comment by dnmeid** [comment]
The Latch checkbox had been a dirty hack from its first day. Look at the many requests for "unlatch without triggering up-actions". There is simply no proper way of synchronizing the state of a machine's property with a toggle button. Everything related to toggling machine properties has to be handeled in the module and requests need to go to the module developer. Toggeling stuff inside Companion is not affected. Since the availability of custom variables and triggers it already is best practice to solve toggeling by setting a variable  (e.g. var = 1 - var) and visualizing it with a feedback. That way you can move the button without breaking logic and can have multiple buttons staying in sync.
Graphics generation will be redone in the near/mid future, it will be a lot easier then to have multiple independent feedbacks on one button.
