### ISSUE TITLE
[BUG] companion.log is no longer created or updated

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2287]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Up until around December 2022, there would be a file in the companion database folder called "companion.log". Additionally, this file would be included when you selected "Export support bundle" on the logs tab in the GUI.

Seems this file is no longer being created or updated?

This happens in v2.4.x as well as v3.x

### Steps To Reproduce

Go to your companion db folder, look for "companion.log". If you find it, it will probably be last updated in Dec 2022.

### Expected Behavior

companion.log should be updated every time you run companion.

### Environment (please complete the following information)

```markdown
- OS:MacOS
- Browser:Safari
- Companion Version: 2.4.1 and 3.0
```

**Comment by Julusian** [comment]
It looks like this is due to how beta is using the `develop` subdirectory inside the main config path. https://github.com/bitfocus/companion/commit/180042dc36a4eec42ca265ccc7a1cd034f71dbcf
This split was done to avoid upgrading the 2.4 config of any users who try the beta before it is deemed ready for mass testing/use.

I'm not sure how best to fix this, as the problem is that the launcher process is the one writing the log file and is unaware that the main process is using this `develop` subdirectory. Either the launcher needs to be aware to write into this subdirectory, or when generating the export bundle it needs to copy the log file from the parent directory. Neither one feels simple or clean to do

**Comment by MeestorX** [comment]
Ok, so where is companion.log written currently?

**Comment by Julusian** [comment]
I think the launcher option to 'open config folder' will take you to the base 'normal' place for it, which will contain the companion.log. Inside that will be a folder `develop` containing the config used for 3.0.
Or if that 'open config folder' takes you into a folder called `develop` then you will want to go out a level.

Re-reading the issue, I don't know why this would have stopped in 2.4. Perhaps try deleting the existing companion.log file? Maybe it is unable to write to it for some reason and is failing silently

**Comment by MeestorX** [comment]
Ok, did some digging. I have Both Companion 2.4.1 and Companion 3 installed on my computer.
Companion v3 is writing to the companion.log in the 2.4 config folder.
2.4 doesn't seem to be writing to companion.log at all as far as I can tell.
And now a new problem - the Export bundle on 2.4 is somehow corrupted.
![image](https://user-images.githubusercontent.com/29129658/213888884-2f354072-7235-4cce-9850-6cc0cc375d9c.png)

**Comment by MeestorX** [comment]
Just confirmed again. When running v3, it's writing to companion.log in the 2.4 config folder. The develop folder is being used however for v3's db.
Maybe check the path for companion.log in v3's code, maybe it doesn't have /develop added to the end?

**Comment by MeestorX** [comment]
Deleted the config folder and re-ran 2.4.1. Here's what the config folder looks like:
![image](https://user-images.githubusercontent.com/29129658/213889892-32bfb296-80f1-4047-ac89-e980a6aa17b0.png)
No companion.log is created.

**Comment by MeestorX** [comment]
After running v3:
![image](https://user-images.githubusercontent.com/29129658/213890010-914e577a-6fe2-496e-a6e7-e8dbc907d42b.png)

Oddly as well, even though I had deleted the companion config folder, when I ran v3, it still remembered what modules I had added.
2.4.1 started like I had never run the program.
Does v3 somehow load the configuration from v2?

**Comment by Julusian** [comment]
> Maybe check the path for companion.log in v3's code, maybe it doesn't have /develop added to the end?

As I said earlier: 

> I'm not sure how best to fix this, as the problem is that the launcher process is the one writing the log file and is unaware that the main process is using this develop subdirectory. Either the launcher needs to be aware to write into this subdirectory, or when generating the export bundle it needs to copy the log file from the parent directory. Neither one feels simple or clean to do

I'm really not sure how worth fixing this is, at some point soon using that subdirectory for 3.0 will be stopped, at which point this will go away by itself 99% of the time. (That subdirectory is intended to be used only for the develop builds, ie the next next release, currently 3.1)

------

For 2.4, are you running companion with the `DEVELOPER` environment variable set? Doing that disables writing the log file. Otherwise I have no idea why this would have broken, as far as I can tell no code near that has changed since april.

> Does v3 somehow load the configuration from v2?

Yes, when first launching 3.0 it will copy in the config from 2.4 (leaving the original unmodified)

**Comment by MeestorX** [comment]
The 3.x launcher is different than the 2.4.1 launcher, isn't it (3.x has the "settings" gear in the top right)? Wouldn't it be easy enough for it to point to the "develop" folder while the 2.4.1 launcher points to the config folder? But, if you say it's not easy, then you would know so never mind!

> I'm really not sure how worth fixing this is, at some point soon using that subdirectory for 3.0 will be stopped, at which point this will go away by itself 99% of the time. (That subdirectory is intended to be used only for the develop builds, ie the next next release, currently 3.1)

Are you saying that when 3.1 is in development 3.0 will overwrite the 2.4 config folder? Won't that be an issue for people running both versions? I would think that for quite a while there will be 2.4 modules that won't work on 3.x or bugs in 3.x modules requiring people to still use 2.4...
If so, I can see a much slower adoption of 3.x while people are still nervous about switching. While you're able to run both, it's pretty safe.
Also, I plan to try and support both for a while at least so I'd like to be able to run both without one affecting the other.

> For 2.4, are you running companion with the DEVELOPER environment variable set? Doing that disables writing the log file. Otherwise I have no idea why this would have broken, as far as I can tell no code near that has changed since april.

How would I check that? I did `env` in terminal (I'm on MacOS) and didn't see an environment variable called `DEVELOPER`.

**Comment by Julusian** [comment]
> The 3.x launcher is different than the 2.4.1 launcher, isn't it (3.x has the "settings" gear in the top right)? Wouldn't it be easy enough for it to point to the "develop" folder while the 2.4.1 launcher points to the config folder? But, if you say it's not easy, then you would know so never mind!

The problem is that using `develop` is defined in the main portion of companion. Making the launcher do the same would be easy, and would make it just as easy to forget to change that part back when we stop using this `develop` folder. I will most likely forget, and it will be corrected once someone opens an issue for the log file not being updated. 

> Are you saying that when 3.1 is in development 3.0 will overwrite the 2.4 config folder? Won't that be an issue for people running both versions? I would think that for quite a while there will be 2.4 modules that won't work on 3.x or bugs in 3.x modules requiring people to still use 2.4...

This is no different to before. Allowing them to run side by side now is more than was possible before. 2.2 was particularly bad at being non-backwards compatible config, and every version since has had some smaller incompatible changes.

But I have been wondering how the path switch will work without 'losing' the config for everyone already running 3.0. so I think I need to rethink this foldering strategy

> How would I check that? I did env in terminal (I'm on MacOS) and didn't see an environment variable called DEVELOPER.

Don't bother. I've just tried 2.4.1, 2.3.1 and 2.2.3 and none of them wrote anything to the log file. It looks like it hasnt worked in a long time for an electron version. so Im not going to touch that

**Comment by MeestorX** [comment]
I'm assuming this is a "to be worked on later" issue, but FYI, the "export support bundle" still does not grab the `companion.log` file in v3. Would be good to have this fixed before I start beta testers with my users, but if it's not something that will be fixed for a long time, let me know so I can give different instructions.

**Comment by Julusian** [comment]
Something else to consider here is that on companion-pi there is no companion.log file being written at all anymore.

I dont know when I will get to looking at this, its more on the scale of a feature to figure out an implementation for than a simple bug fix

**Comment by krocheck** [comment]
I remember needing to make a change to `companion.log` because the write location was the execution directory instead of the config directory and on most OS's was getting a write permission error.  I think I wrote the fix into the v3 branch at some point but never backported it.

**Comment by Julusian** [comment]
As we are sticking with this subdirectory structure, it is simple enough to look upwards a folder to find the logs now. 
However, this won't work for companion-pi, as we are leaving the logging for this to the os
