### ISSUE TITLE
[BUG] v3 search connection gives ugly results

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2309]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The results of search in the connection tab gives ugly results.
e.g. typing "etc" gives many results which haves nothing to do with "etc".
On 2.4.1 I get only one exact result "ETC Eos"

### Steps To Reproduce

Go to connection tab, fill the search field with a know connection.

### Environment (please complete the following information)

```markdown
- OS: macOS 13.2
- Browser: Safari 16.3
- Companion Version: latest beta
```

**Comment by Julusian** [comment]
This is because of #2258. To provide better suggestions when things arent typed exactly. For example 'artnet' would find nothing, as it is written as `art-net`
I think the real issue here is that when this filtering is done we are sorting it by name rather than by the weighting the fuzzy search library gives. so the best match will likely end up halfway down the list rather than at the top

**Comment by sstaub** [comment]
The problem I see, that there are results which doesn't content the string "etc" for my example.

**Comment by Julusian** [comment]
I have changed the sort order, to show the 'best' results first, and Ive changed the threshold used.
For `etc` it now shows just the one, but for other cases it should still do fuzzy searching as intended
