### ISSUE TITLE
[BUG]Variables dropdown selection goes off screen

### ISSUE THREAD

**Issue by noiseboi** [bitfocus/companion#2344]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With button label set to expression, adding variables produces drop down selections as expected. The dropdown selection moves further to the right with each additional operand to the point where the dropdown selection is off the screen.

### Steps To Reproduce

Try typing an expression adding several variables to the button text.

![image](https://user-images.githubusercontent.com/88212362/220756719-3159997a-26d1-4465-9c04-af6e66aa3368.png)

### Environment (please complete the following information)

```markdown
- OS:W10
- Browser:Chrome 110
- Companion Version:3.0.0+5681
```

**Comment by Julusian** [comment]
This looks to be a bug with the library we use for that input suggestions. Maybe this can be fixed by setting `positionMenu: false` and setting a position ourselves?

That library is rather unmaintained, and has caused us other problems so it might be time to properly think about replacing it. I haven't managed to find a suitable alternative though, and don't particularly want to write our own version of it.

**Comment by Julusian** [comment]
This has been redone in the betas so this should no longer be a problem.
