### ISSUE TITLE
[BUG] Internal action/feedback comparisons can't compare timecode 

### ISSUE THREAD

**Issue by bhckrd** [bitfocus/companion#2372]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to use "internal: button press and release if variable meets condition" to chose between firing 2 different buttons based on the "time of day (HH;MM) (internal:time_hm)" variable. I would like Button A to be fired if the time is any time between 00:00 and 10:45, and Button B to be fired if the time is anywhere between 10:46 and 23:59. The (HH:MM) variable works if I use the "=" or "!=" operators, but does not seem to work with the "<" and ">" operators. The same thing happens if I try the (HH:MM:SS) variable. I tried a few other time of day variables for (HH) and (MM) by themselves, and all of those operators seemed to work as expected. The issue seems to be in the variables that add ":" between HH, MM, and SS.

Is there something I might be missing in how I am supposed to use these operators and the ":", or is this a bug that needs fixed?

Note, I am running 2.4.2 and have tried values of 13:27 and 13:27:00, both of which seemed to have the bug described above.

### Steps To Reproduce

1. Create a "Regular Button".
2. Use a "Press action" and set the action to "internal: Button Press and Release if Variable meets Condition".
3. Set "Variable to check" to "Time of Day (HH:MM) (internal:time_hm)" or "Time of day (HH:MM:SS) (internal:time_hms).
4. Use the "Learn" button to learn the current internal "Value".
5. Edit the value to be either greater or less than the current value (i.e. change 13:27 to 13:30 or 13:25).
7. Use the "<" or the ">" operators to try a button press on the current page based on the time variable.
8. Observe that the button press does not work.
9. Try changing the operator to "=" or "!=" and the value as appropriate for testing each variable.
10. Observe that the "=" and "!=" operators work as expected.

### Expected Behavior

I would expect that if the current time is 13:27 and the time variable is set to press "Button A" when the time is < 13:30 or "Button B" when the time is > 13:30, that "Button A" would be pressed. Likewise, if the time was after (>) 13:30, that "Button B" would be pressed.

### Environment (please complete the following information)

```markdown
- OS:macOS Monterey, Version 12.6
- Browser: Safari Version 15.6.1
- Companion Version: 2.4.2
```

**Comment by Julusian** [comment]
I don't think there is anything for us to do here. This is a limitation because we aren't trying to parse times in strings, and doing so adds ambiguity. What should `10:20:30 < 40:50` do? That `40:50` could mean `HH:mm` or `mm:ss`.

In 3.0, it is possible to achieve this with the action `Button: Trigger press and release if expression is true`, and an expression like `timestampToSeconds('10:20:30') < timestampToSeconds('40:50:00')`, which is wordier to write, but doesnt have the same ambiguity. That function doesnt handle anything other than `HH:mm:ss` format, but that can be worked around with something like ```timestampToSeconds(`${$(internal:custom_my_var)}:00`)```, and we can look at supporting different formats in that function more easily

**Comment by bhckrd** [comment]
Not sure I follow... I'm not trying to mix the hh:mm and hh:mm:ss variables. I'm using hh:mm and setting the value in that same format so that it would check if the variable I set "10:45" is < or > than the internal time. If it were 10:30, I would expect it to say 10:30 < 10:45, therefore press "button a". Is that not how the variable works?

**Comment by dnmeid** [comment]
> Is that not how the variable works?

Correct, that is not how the variable works. 10:30 is handeled as a string by Companion. Comparing strings will not give a valid result in your case. This is the intended behavior and not a bug.
As said by Julusian, what you want to do, can be done in v3. You need additional logic which first transfers your timcode string to a numeric value and then compares the numeric values.

Just for your usecase in v2 there is an alternative way of doing it.
You can set up one variable to distinguish between day and night, e.g. `isDay` 
Now you create two triggers to set that variable, one trigger sets it to `1`at 10:45 and the other trigger sets it to `0`at 00:00
You can control your action now by comparison against isDay.
Only drawback of this workflow is that the variable will only be 100% correct after one of the triggers has run the first time.

**Comment by istnv** [comment]
> 10:30 is handled as a string by Companion. Comparing strings will not give a valid result in your case

 `'10:30' < '10:45'` as a string comparison returns `true` and should work.
A post on facebook wants to check for < 10 seconds remaining in a VLC playback with a feedback to turn a button red. Comparing the time remaining variable to `<'00:10'` or `<'00:00:10'` both fail to trigger the feedback.

**Comment by Julusian** [comment]
> `'10:30' < '10:45'` as a string comparison returns true and should work.

True, but we are explicitly comparing them as numbers, which results in `NaN < NaN`.  
I can't say why we are forcing the comparison to be done as numbers, so I can't be sure that changing it wont introduce bugs that break existing configurations.

As 3.0 is the latest release, and there is an alternate solution that makes the intention and expected behaviour explicit and safe, I don't think we should risk breaking this in other ways right now.
