### ISSUE TITLE
When I open the app, on the configuration wizard page the center of the pages says "Companion is Locked" I have no idea why and am unable to do anything. Please help[BUG]

### ISSUE THREAD

**Issue by Steve072451** [bitfocus/companion#2393]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
This comes up fairly often on facebook. 
![image](https://user-images.githubusercontent.com/1327476/227736749-90a9f708-de40-40ec-8198-5b4b319020eb.png)


If you could tell us what the password was set to, either the exact value, or a vague description (such as saying it was a real password, or what you thought but with a typo) that would be helpful so that we can figure out why this keeps on happening for people.  
At the moment, there is either a bug that a minority of users are encountering, with no ideas on why/what is causing that, or a lot of people are asking for how to default this crude authentication, and these instructions are defeating the purpose of this feature

**Comment by marvelbug** [comment]
I am also having this issue with my version of Companion

**Comment by sirhaaty** [comment]
Same error happens to me and idk how to solve it, tryed everything and nothing solve it

**Comment by video-en-direct** [comment]
same here on a mac book pro intel
![Capture d’écran 2023-12-04 à 20 01 32](https://github.com/bitfocus/companion/assets/152900912/ddec6a6e-b457-48cb-8ab2-bc772cbe3cce)
