### ISSUE TITLE
Find Devices

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#240]
Find Devices. 

If you could select an IP range and it could find the instances for your network.

**Comment by dnmeid** [comment]
Which instances? For which network? Do you mean a module/all modules should be able to scan an IP range and detect if there is a device answering with the right protocol?

**Comment by hadphild** [comment]
Basicly and Auto detect on the Main Network IE if the DHCP Range is 192.168.1.X to 192.168.1.254 with 255.255.255.0 then it can try and find all devices connected and work out what intence it needs to control.

**Comment by dnmeid** [comment]
I really don't know how this should be accomplished.
1. Not all installations are using DHCP
2. How should Companion know the DHCP range
3. There can be hosts even outside of the DHCP range
4. How do you want to "find" a device? Not all devices respond to ICMP or whatever.
5. How do you want to determine what kind of device it is? Make a connection attempt with every module? Only a few devices are identifying themselves properly, a open socket doesn't mean anything. How long do you want to wait until you try the next protocol?
Only a small percentage of the devices can be found that way at all, some people may think the device isn't there just because they can't find it. Show control isn't plug and play.

**Comment by monoxane** [comment]
I feel like this is totally impractical to implement reliable and efficiently because, while hardware is usually fixed port, most of the software instances controllable by companion have user defined ports, meaning companion would not only have to scan all its for all known service ports, but actually scan every ip on the subnet and every TCP and UDP port on each IP, I don't know if you've ever tried that with nmap but even a /24 can take upwards of an hour depending on how many devices are online in the subnet. 

Then there's the instance mapping issue of what if an ATEM and a hyperdeck use the same port? Companion would have to connect to that device and issue a command that would determine what the device actually is, something that will increase the scan time significantly, not to mention those applications that use standard OSC on user configurable ports with no way to determine what is actually running on them without a connection and probably a custom packet that responds with "I am QLab" or something of the sort, things out of the range of the Companion project.

**Comment by hadphild** [comment]
Thinking another way. Are there Items that send out broadcasts that could add themselves easily.

**Comment by dnmeid** [comment]
Not that many. Artnet is an example and the Artnet module already automatically detects broadcasted universes. I think if a device supplies zeroconf or bonjour or any device discovery mechanism it should be left to the module to use it. But the user still has to add the instance himself. I don't see any reliable mechanism of "I push one button and my show control system is setting up itself".

**Comment by dnmeid** [comment]
That way it would fail faster but fail anyway.
