### ISSUE TITLE
Capacity to PIN lock only specific devices

### ISSUE THREAD

**Issue by AlexWHughes** [bitfocus/companion#2444]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Working on a show where it would be great to have the capacity to set a PIN lock for Streamdecks to only apply to certain devices. This would allow us to use the units in public facing areas with secure access but white list devices that we need constant access to without a pin that are back of house. 

The workaround is to run two installs of Companion

### Usecases

As above. Great in mixed environments where to certain devices need to be locked while others don't. 

Helpful for control positions where you have certain operators that want to lock their panels. (Can have all same PIN)

**Comment by kraves-oz** [comment]
There is a workaround for this, by removing the general navigation buttons off those particular pages.  Then use the default page option in settings for each SD.

**Comment by Julusian** [comment]
@kraves-oz I dont think that helps here. In this situation they might want to be using the same set of pages, but some want to be subject to the pincode locking and possibly auto-timeout with others not doing that.

Depending on how the locking wants to be handled, it might be possible to achieve this today by being careful with which panels are issues the lock and unlock commands, but at startup every panel does get locked.

Eventually we should probably make it so that different pincodes can be used, but I think that would be best to do following #570, as that starts on a concept of grouping and give a sensible place to do this extra configuration.

-----

I can think of another use case here.

Having a streamdeck behind the bar for the bar-staff to use to do a couple of basic things, which wants to never be locked. On the same setup as some streamdecks at FOH which wants to be locked when the tech steps away.

**Comment by Julusian** [comment]
This is now possible in beta. In the settings for each surface, it can be marked as 'never pin code lock'.
When this is enabled, the surface will remain unlocked while other surfaces can do the usual lock flows. 

![image](https://github.com/bitfocus/companion/assets/1327476/b07911c2-f9be-4220-908b-3904ec8c157a)

**Comment by AlexWHughes** [comment]
Amazing work. I'll give it a test shortly
