### ISSUE TITLE
[BUG] Unable to launch on Mac OS X

### ISSUE THREAD

**Issue by nathcoad** [bitfocus/companion#2488]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Receive popup message "Companion is unable to start" when launching Companion application. The red splash screen shows where it says "waiting for webserver..." and after 2 or 3 seconds the popup shows.

The following error is found in the companion log file (in the ~/Library/Application Support/Companion/logs folder):
```
dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Companion.app/Contents/Resources/node-runtime/bin/node (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib2023-06-19T02:57:46.093Z Application: Restart Count: 3dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Companion.app/Contents/Resources/node-runtime/bin/node (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

I assume this is related to the old version of hardware and OS X that I am running, but version 2.4.2 runs fine.

### Steps To Reproduce

1. Download latest companion installer for Mac, intel version
2. Copy to Applications folder and launch
3. Error is shown as described in bug report above

### Expected Behavior

Companion should start web server and execute normally.

### Environment (please complete the following information)

```markdown
- OS: Mac OS 10.13.6 (High Sierra)
- Browser: Chrome 114
- Companion Version: 3.0.0 rc1 5909
```

### Additional context

Based on the error logs I assume the versions of libraries used are not compatible with this old version of OS X, and it may be that you are unable to support such an old version.

**Comment by Julusian** [comment]
Thanks for including the log snippet, that is really helpful for understanding the issue.

Unfortunately I don't think there is anything we can do here. This has come as a consequence of some reworking of the architecture of the application, as well as updating the version of nodejs we use to v18 which requires macos 10.15 https://nodejs.org/en/blog/release/v18.0.0#toolchain-and-compiler-upgrades

In theory it could be possible for us to build nodejs ourselves to avoid this, but that will be a lot of complexity and has a high risk of something else being done wrong causing other issues.

What we can do is to do some os version detection, so that we can inform users that this version of macos will not work instead of ending up with this cryptic crash loop. I shall leave this open for doing that

**Comment by Julusian** [comment]
Beta 5969 will now refuse to run and will instead show a dialog like below to make it clear that it is unsupported.
![image](https://github.com/bitfocus/companion/assets/1327476/9f489110-819d-4da5-83ca-5a74dddb51e2)

This is also included in the release notes
