### ISSUE TITLE
Module Request: Calling presets on a Lightware mx16x16DVI matrix

### ISSUE THREAD

**Issue by SalkinDK** [bitfocus/companion#259]
**Describe the feature**
The ability to save and recall presets on the matrix

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**
useful info here https://lightware.com/pub/media/lightware/filedownloader/file/MX_DVI-Plus_Users_Manual_v3.0.pdf page 39

**Usecases**
As a remote to trigger preset to back-up machine etc...

**Comment by haakonnessjoen** [comment]
Would you be able to give me access to a mx16x16dvi matrix at one point, over the internet? The LW2 protocol is not that well documented, and it seems that I need to manually try to figure out how many presets the device has. Since the module I wrote is trying to be a general LW2 module, not locked to only one type of matrix. The last manual I read did not mention any presets in LW2.

**Comment by SalkinDK** [comment]
I think it is going to be difficult to get you access, since I am just a freelancer.
But I will try to see if I can sniff some of the traffic going from the Lightware Device Controller software next week where I am doing a show with two matrixes.
In the software it shows 32 presets, see picture. (https://imgur.com/a/oQ6DMVK)
Don't know if you can get any info off that program? you can download it here http://software.lightware.eu/software/

I don't know if it uses the LW2 protocol?

**Comment by haakonnessjoen** [comment]
I'm interested in knowing how it would answer if I ask for a preset that does not exist, etc. That way I might be able to loop my way to the conclusion of how many presets the device supports. The LW2 protocol is very mediocre, and consequently expects you to design your system around each device, instead of allowing you to make general support, like we want.

Next time you have access to one, please try to connect via tcp to it on port 10001, if you are on a mac, use nc x.x.x.x 10001 to connect to it.

Then try to issue the command: {pname#33=?}
Swap 33 with 1, or 100, to se the different responses of valid and invalid preset numbers. We might be able to use this to figure out how many presets it has, if it has decent error reporting.

I think the program just knows about all matrixes, and internally adjusts the amount of presets, knowing the devices by name. We do not want to keep updating a list of known devices if we can skip it.

**Comment by SalkinDK** [comment]
Now I got hold of a matrix, and could try some things.

`{pname#32=?}
(PNAME#32=Preset32)
{pname#33=?}
(ERR04)
{pname#1=?}
(PNAME#1=Preset1)`

`{%1}
(LPR01)
(ALL 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01)
{%2}
(LPR02)
(ALL 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32)`

So my conclusion would be that all the matrixes have 32 presets, and can be easily called with the {%"preset number"} command.

Any more things I should try out?

**Comment by haakonnessjoen** [comment]
Great! Just one thing. If you rename a preset from another UI, while still connected. Do you get a message updating the TCP connection with the new preset name automatically? (like events) Because I think it does send events when you route/xpoint at least.

**Comment by SalkinDK** [comment]
Here is the responds for some routes a preset preview and two times preset renames, done through the Lightware Device Controll.
So yes I does sends events when things change.

`(O01 I01)
(O02 I01)
(O03 I01)
(O04 I01)
(O05 I01)
(O06 I01)
`

`(VP#1 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01)
(VP#3 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01)
`

`(PNAME#3=preset3)
(PNAME#3=RENAME)`

**Comment by haakonnessjoen** [comment]
Great, that means that we could add feedback :) I will look at this, and presets soon.

**Comment by SalkinDK** [comment]
Wonderful. Looking forward to it.

Not to put pressure on you or anything, but will it be in the next days or what?
I have a matrix here until thursday, so I can test if needed.

**Comment by SalkinDK** [comment]
You ROCK!
I have just tested with the newest nightly and everything works like a charm here!

Any possibility to donate a beer or two to your awesome team?

**Comment by willosof** [comment]
Beer is expensive in Norway! 😅

**Comment by willosof** [comment]
https://opencollective.com/companion
