### ISSUE TITLE
50-companion.rules too specific on "plugdev"

### ISSUE THREAD

**Issue by sausix** [bitfocus/companion#2635]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`/etc/udev/rules.d/50-companion.rules:31 Unknown group 'plugdev', ignoring.`

plugdev is Ubuntu'ish (or Debianistic?) and does not exist on some/many distributions.

Since mode is set to 666 anyway on each rule, setting the group could be omitted or am I wrong?
`KERNEL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE:="666"`

### Steps To Reproduce

Install the rules file on Arch Linux

### Expected Behavior

No warnings in the logs

### Environment (please complete the following information)

```markdown
- OS: Arch Linux
- Browser: Not relevant
- Companion Version: git
```

**Comment by Julusian** [comment]
I'm not sure what is best here.  
While I think your suggestion should be ok, I am not 100% certain, and part of me doesnt like that we are using `666` as the permissions, and wonders if that should be changed to `660` which seems to be a more normal/sensible permission level.  
But of course doing both of those changes will break things, so I guess we need to choose one change and go with that.

**Comment by sausix** [comment]
Setting the device to 660 and changing the device group to an existing one would be perfect.

660 should at least be done for pure security reasons. It will probably break those installations especially not having the `plugdev` group. But that could be patched downstream on non Debian systems.

What about creating a new user-group `companion`? The daemon running as service could run as a dedicated user.
Doesn't companion have systemd support? It's common to run a service under its own user there anyway. At least on Linux. At least it should not run as root in any case.

**Comment by Julusian** [comment]
A problem we will encounter here is that there are two flows to consider, with udev rules being needed for both scenarios:

1) Running Companion as a systemd service
  I think the install script we recommend will already be creating that group as part of creating the user, so it wouldn't be hard to change the rules to reference it.

2) Running Companion as a desktop app
  For this it sounds like we should be using `TAG+="uaccess"` instead of a group https://github.com/libusb/hidapi/blob/master/udev/69-hid.rules#L30-L36 https://bugzilla.redhat.com/show_bug.cgi?id=815093

So I guess we need two different udev rules files then, one using the tag approach for desktop usage, and one using the group.

**Comment by Julusian** [comment]
I don't like having two udev rules files, but there are two files now with the readme updated to specify which to use
