### ISSUE TITLE
Button text and style lost on restart

### ISSUE THREAD

**Issue by otelom** [bitfocus/companion#2640]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a restart companion button that I change its text to "cancel" once pressed and on step 2 I have actions to cancel.
Before the restart command I do set up the propper text and background and I see that it changes but when companion restarts, it comes back with "cancel" on a red background.

The only way around this I found was to add a trigger on startup.

### Steps To Reproduce

Setup a button like mine:

![image](https://github.com/bitfocus/companion/assets/12788894/b16f8a0c-ea29-4b4e-861e-ae123198f6fc)

Press it and when companion restarts, you'll see that your button is showing "Cancel" on a red background.

### Expected Behavior

It should keep to the text it was before restarting "Restart Tablets"

### Environment (please complete the following information)

```markdown
- OS: Windows 10 Pro x64
- Browser: 119.0.6045.107 official x64
- Companion Version: 3.1.2 (3.1.2+6243-stable-05c37a10)
```

**Comment by Julusian** [comment]
I want to say 'this is by design', but I am unsure if that is the case or if it is just 'this is how it has always worked'
These actions are directly changing the style of a button. Changing this behaviour will break the workflow of many other users who rely on these changes persisting.

I would suggest replacing this flow with a custom variable, or doing the check based on the current step of the button

I think the simplest is to use the feedback that checks the current step of the button. When it is on step 2, then change the style to how you want.

Or create a custom variable which defaults to 0 at startup.
Instead of modifying the button style, you set a custom variable to 1 (or back to 0 to put it back to default style).
Then using the internal 'check variable' feedback, you can make the button show `cancel` and be red when that variable is 1.
