### ISSUE TITLE
Surfaces Scan and Disconnect [BUG]

### ISSUE THREAD

**Issue by Tripbacca117** [bitfocus/companion#2643]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When Companion scans all the Streamdecks, it sees all of them and immediate disconnects all of them. Happens even after rescanning.

Update: I rescanned after posting and it suddenly held the connections.
![Screenshot 2023-11-12 at 7 22 01 AM](https://github.com/bitfocus/companion/assets/150598600/60131b63-692f-40fc-bd70-9128f1a59652)

### Environment (please complete the following information)

```markdown
- OS: macOS Ventura 13.5.2
- Browser: Google Chrome
- Companion Version: 3.1.2
```

**Comment by Julusian** [comment]
Is there anything in the log?
Does it work if you have less streamdecks connected at a time?

This sounds like something specific to your environment in some way

**Comment by Tripbacca117** [comment]
> Is there anything in the log? Does it work if you have less streamdecks connected at a time?
> 
> This sounds like something specific to your environment in some way

The logs just show the disconnects. No extra information from there. 

It had worked just fine until I shut down my system. When I rebooted, it started failing connections. 

I rescanned USBs a few minutes ago and it held the connections.

**Comment by cpuguru07** [comment]
I have this issue as well. Approx. 10 surfaces (mostly SD XL, a few standard SDs) connected across maybe 6 instances of Satellite (5 Windows and 1 RPi). Running a fairly complex Companion setup with 36 module Connections, custom variables, heavy use of functions, etc.

Seems to happen when Companion server PC (Windows 11) spikes at 100% CPU. Running in VMware (no other VMs on this host, yet), so doubled the CPUs (2 sockets with 4 cores each) and RAM (16GB). Normally sits around 20-30% CPU/RAM usage, but occasionally spikes and stays up over 80% CPU - this is usually when issues occur. Companion usually sits around 1,350MB of RAM use.

This instance of W11 is dedicated to running Companion (was very unstable trying to run it on an end-user PC since v3). Sometimes restarting Companion fixes it temporarily, sometimes it requires a full Windows reboot. Sometimes it works fine for a while after a full reboot, and sometimes it happens again within an hour or so.

**Comment by Julusian** [comment]
Is this still a problem?

I'm not sure what to make of this. We only close the streamdecks when they report an 'error', meaning that either a read or write operation has failed for some unknown reason

------

For the issue with satellite, that sounds rather different and is not surprising that satellite connections are being dropped when cpu spikes to 100% for periods.
I can't explain that either, other than some work should probably be put into performance testing of companion
