### ISSUE TITLE
[BUG? / DOCS?] Satellite API Ping Requirements

### ISSUE THREAD

**Issue by hrueger** [bitfocus/companion#2668]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using the Satellite API with a custom client implementation. Recently, a user reported that it is constantly disconnecting. The companion logs show:
```
23.11.29 17:28:17 Service/Satellite/::ffff:127.0.0.1:57068: socket timeout
23.11.29 17:28:17 Surface/Handler/[name]: [name] disconnected
```

I believe I'm running into the [socket timeout here](https://github.com/bitfocus/companion/blob/05c37a108bc515d3983e2be9cea73c3145719e26/lib/Service/Satellite.js#L237-L242). The question is - why? It was working fine with earler versions (probably something like v2 though 😅)

What probably fixes it (I think) is to send PING messages from the client, for example every 3 seconds. Is there a new requirement to send PINGs which is not documented [here](https://github.com/bitfocus/companion/wiki/Satellite-API)?
If sending PINGs is the official solution, what interval do you recommend? Thanks in advance.

### Steps To Reproduce

1. Build a simple Satellite client which just connects to the socket, registers a device and listens for incoming data
2. Observe how the tcp connection is killed from the server (companion) after 5s

### Expected Behavior

The connection is kept open or a requirement for sending PING messages is added to the Wiki.

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Firefox
- Companion Version: 3.1.2 (3.1.2+6243-stable-05c37a10)
```

### Additional context

My Satellite Client is actually adding three devices, though I don't think that this is related in any way.

**Comment by Julusian** [comment]
I believe this would have changed for https://github.com/bitfocus/companion/issues/2054 in https://github.com/bitfocus/companion/commit/385edd3271ba57314ecc90c416d1f5dafab37628 

I thought that the documentation did say that clients are expected to ping at an interval, but it appears that it does not. Ill add something there.
companion-satellite is pinging every 100ms, but 3 seconds is probably fine too.
I took the view that it needs to be often to detect network drops, as users will not be happy when they press a button and nothing happens because the connection was stuck and it hadnt been detected yet.

**Comment by hrueger** [comment]
Sounds great, thanks!
