### ISSUE TITLE
[BUG] internal: Actions: Abort all delayed actions on a page

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion#2877]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Delayed action is not interrupted even if you use command:
**internal: Actions: Abort all delayed actions on a page**

### Steps To Reproduce

1. Create button A with dealyed action for 15 seconds. This action will press and release button B: 
![image](https://github.com/bitfocus/companion/assets/22023099/32ef8a3d-a5b4-4cdf-8b9f-6122f896e993)
2. Create button B: 
![image](https://github.com/bitfocus/companion/assets/22023099/73d50b89-fcf9-4622-9a79-87e26c44a740)

### Expected Behavior

Push the button A and in time less then 15 seconds press button B. The delayed action on A should be interrupted. It does not work :-(

### Environment (please complete the following information)

```markdown
- OS:Win 10
- Browser: Chrome last
- Companion Version: 3.3.0
```

**Comment by Julusian** [comment]
As a workaround, you can tick the 'use variables for page' box, and type `35` into that field. It will then work as expected.

The logic handling that checkbox was faulty, causing it to always take the behaviour of when it was checked.

This is fixed in the betas, and will be in a 3.3.1 release at some point
