### ISSUE TITLE
[BUG]:  Module registration failed Error: Call timed out

### ISSUE THREAD

**Issue by G-Hansen** [bitfocus/companion#2890]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I keep getting an "error: Module registration failed Error: Call timed out" error.  It is on multiple modules. I think it is a wrong setting but I can't change the configuration because it gets stuck in a loop when enabled.  And I can't edit the configuration when disabled.  It is the Pro Presenter and Roku modules.

### Environment (please complete the following information)

```markdown
- OS: MacOS 13.0
- Browser: Chrome
- Companion Version:3.3.0+6991
```

**Comment by Julusian** [comment]
I can't say for certain for those modules, but this usually happens when a module is either crashing or it's `init` method doesn't complete within the timeframe we give it.
So I suspect this should be reported against those modules rather than companion itself

Could you provide the log from the connections which aren't working?
The `>_` icon in the connection list will open a more detailed debug log, you will want to disable and re-enable the connection with that view open to get a populated log window.

**Comment by Julusian** [comment]
With the information provided, I don't see anything that we can do to avoid this happening. If more information is provided this can be revisited
