### ISSUE TITLE
[BUG] Trigger Condition is delayed

### ISSUE THREAD

**Issue by J0h4NNes83Ere** [bitfocus/companion#2976]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to trigger an overlay in OBS everytime Cam3 on my Atem mini is **cut to** program. 
However, the trigger only activates when i **cut away** from Cam3. 
I have tried different Events, Conditions and Actions, but everytime the trigger activates only when i cut away. The trigger is always one step delayed. 
I dont believe its the Atem module, as tally / feedback works as expected. OBS set scene also works fine. 
Maybe the Condition requests cached data? 

### Steps To Reproduce

Event: on variable change: atem:pgm1_input
Condition: Atem M/E1 Program Source: Camera 3
Action: OBS set Program Scene: "Overlay"

### Expected Behavior

When Cam3 is active on PGM, the trigger should change the OBS scene

### Environment (please complete the following information)

```markdown
- OS: Win 10
- Browser: Firefox 127.0.2
- Companion Version: 3.3.1 (3.3.1+7001-stable-ee7c3daa)
- OBS 30.2.2
- Atem Mini Pro 9.5.1
```

**Comment by Julusian** [comment]
I'm not able to reproduce this. I have a pair of triggers setup as shown in the screenshot (different inputs and values for each) and the custom variable is being updated when pressing the atem buttons
![image](https://github.com/user-attachments/assets/94a5dea2-8e7c-4ff7-b79c-410c67fed98d)

**Comment by Julusian** [comment]
Oh, hang on. You're using ` Condition: Atem M/E1 Program Source: Camera 3`.

Which means that this is expected behaviour. Feedbacks and variables are two separate systems, running their own cycles and speeds, so it is expected that they will report their updates at slightly different times to companion, causing issues such as this.

While I can understand this is confusing or annoying, changing this behaviour would require a major rearchitecture of how both feedbacks and variables work, and then updating every module to use this new architecture. This isn't impossible, but will take years (getting every module updated to the api introduced in 3.0 is still ongoing, over a year after release of 3.0) and there are other ways to do what you want, so this isn't worth the effort at this time.

You can either do it like I have shown, using just variables for both the condition and event, or swap out the event to `On condition becoming true` and it will work fine.
