### ISSUE TITLE
Add an "Internal" action of "Button: Set text size"

### ISSUE THREAD

**Issue by tc2290** [bitfocus/companion#3123]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

Add an "Internal" action of "Button: Set text size". This action should change the size of the text on a button.

### Usecases

This would be very useful in helping differentiate between button selections. For instance, I would like the currently active button in a group to have a larger text size to help emphasize what is selected. "Auto" should also be an option in this action.

**Comment by tc2290** [comment]
### Without text size
![Image](https://github.com/user-attachments/assets/1cc3e122-dc8f-4463-8e7a-8b3e5068d490)

### With text size
![Image](https://github.com/user-attachments/assets/33072a76-520c-4132-943b-f15dd36af873)

**Comment by thedist** [comment]
This is already possible with Boolean feedbacks

![Image](https://github.com/user-attachments/assets/05b3064e-58fa-4942-8cfa-1838c9432299)

So rather than using an action to trigger the size change, you would just set a custom variable to a value (eg, `all`, `Voc1`, `Voc2`, etc...) then just have the feedback on each button, and check if the custom variable matches the value for that button, and add the `Font Size` style for the size you want when the feedback is active.

**Comment by tc2290** [comment]
Got it. Didn't think to look for that as a feedback option. The module I'm using does have boolean feedbacks I can use for that.
