### ISSUE TITLE
[BUG] Unable to edit dupliacated button step

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion#3125]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When you dupliacte STEP, you are not able to edit/change values in SELECT inputs. See bellow...

### Steps To Reproduce

1. Create button with 1 step action. Add some actions where you have form input:select
2. Dupliacte the step
3. Try to edit form input:select

![Image](https://github.com/user-attachments/assets/070ff255-50fd-4336-9888-63d935953028)
![Image](https://github.com/user-attachments/assets/d6725916-89ad-409d-b366-cfdc44f875b9)

It is not possible. Something locking the selection on value you had set in STEP 1.

Workaround: Create new step without duplicating.

### Expected Behavior

Normal selecting... :-)

### Environment (please complete the following information)

- OS: Win10
- Browser: Chrome last ver
- Companion Version: 3.4.3

### Additional context

I found the bug in previous update 3.4.2. Before this version I think it was fine.

**Comment by dnmeid** [comment]
Investigation shows that the step is duplicated but the actionId is not updated. This impacts not only the dropdown, but all inputs. You just don't notice on a textinput.
The server does not process the change and answers the request with [null, false].

Fixed in 9162a62ce69e5c0454cacba38f4345f7f143b3bf by first updating the action IDs and then commiting afterwards.
