### ISSUE TITLE
[BUG] Trigger for Tally using vMix and Panasonic AW-UE150

### ISSUE THREAD

**Issue by FabrizioBocci** [bitfocus/companion#3177]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hello, i'm trying to setup some triggers to activate and deactivate Tallies on Panasonic PTZ cameras AW-UE150 using vMix and StreamDeck and Comanion 3.4.3
I have created a trigger for ON and one for OFF, and the Action perfectly works.
For condition i have used vMix General - Input State, type playing and Input name or number, as of CAM1 ie.
If i manually press the test action button it's ok.
Switching cameras doesn't work.
The funny thing is that focusing the input field in the Companion GUI makes it temporary work.<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/143837f6-290d-4e9a-a1de-1e1ca0e0d7bb" />

### Expected Behavior

Turn tallies ON and OFF accordingly with selected camera

### Environment (please complete the following information)

```markdown
- OS: Windows 11
- Browser:Edge or Chrome
- Companion Version: 3.4.3
```

**Comment by FabrizioBocci** [comment]
Quick update:
i have also tried to use a variable as condition: $vmix:mix_1_program_name 
The variable is correctly updated when i switch input in the variable list, but trigger is not fired on the change, sometimes randomly when i play with settings.
I have setup the condition as $vmix:mix_1_program_name = CAM1 (or CAM2 as input names) , no luck

**Comment by thedist** [comment]
First off, the input state feedback shouldn't be used for this type of trigger because in almost all workflows a camera input will always be playing, it's not normal to pause a camera input even if they're not in preview or program, unlike a video file input which usually is paused when not in program.

As for using the `internal: Variable: Check value` condition with the `mix_1_program_name` variable, I'm not experiencing any issues and it correctly fires the trigger when the input name set in the condition is live in `mix_1_program_name`.

Make sure you check your Companion logs with `debug` logging enabled as that'll show if the triggers are firing or not, as if they're firing but the action isn't working it could indicate an issue with that action rather than the condition or the trigger itself.

**Comment by FabrizioBocci** [comment]
@thedist thanks for your message.
In the log i don't see the trigger being fired, it happens once when i disable and re-enable it, than nothing.
I have also used the tally variable instead of program_name, same result. 
The action is performed if tested manually with the TEST button, just the event is not bein fired, but in the variable tab i can see values changing properly.
Anything else i could check about triggers?

**Comment by thedist** [comment]
Just to check, you have the Trigger itself, the event, and the condition, all toggled on?

**Comment by FabrizioBocci** [comment]
Everything is enabled.
I have tried this new version with boolean variable, same result, the trigger is not fired, with the exception of when i manually disable the condition. on the toggling of the enable switch it's fired

<img width="1117" alt="Image" src="https://github.com/user-attachments/assets/2b29e258-bf21-4d85-b337-926265857453" />

**Comment by thedist** [comment]
Try using the `internal: Variable: Check boolean expression` condition, with an Expression such as `$(vmix:input_test_mix_1_tally_program) === "true"`. Again that works fine for me so I have no reason to see why it wouldn't work for you.

**Comment by FabrizioBocci** [comment]
@thedist fantastic!! Thank you so much. This way works like a charm. Now i can see triggers being fired even for cameras not connected. I don't know why using other methods/variables doesn't fire them
