### ISSUE TITLE
Timer/clock internal module

### ISSUE THREAD

**Issue by DaveShep** [bitfocus/companion#389]
**Describe the feature**
A module that exposes the following internal dynamic variables and support functions to provide a timer and clock to solely appear on the streamdeck:

var Time of Day
var Timer hh:mm:ss etc.
void resetTimer(minutes)
void Go()
void resetTimer()
void Pause()
etc.

This will provide a building block upon which button actions can be fired after a delay. Also bear in mind how allowing modules to fire button actions might be implemented.

**Comment by BasilChessman** [comment]
This would be great for turning on projectors in the morning.  They could be on and warmed up by call time.

**Comment by onfire4g05** [comment]
Has there been any dev work on this request / adding a built in scheduler of some sort? We use Companion with another piece of automation software, and the schedule is the only portion that Companion doesn't do for us.

So... if not, I'd like to explore mocking something up for how I think it could work and possibly work on it if that's ok?

**Comment by josephdadams** [comment]
@onfire4g05 there hasn't been. You are more than welcome to mock something and prototype it! That's why Companion is open source! :)

Personally, I use Cronicle running on a server with a plugin for Cronicle to trigger Companion buttons, so that I can keep all of my scheduling centralized since I have many Companion installs. https://github.com/josephdadams/CroniclePlugins

**Comment by onfire4g05** [comment]
Here is a very rough markup of the interface side. My thought is to start with **only** the TOD type, and then expand to include timers and other functionality later.

Timers would be expandable to allow for multiple, named timers. Then inside the button configuration you would have an action that allows you to manipulate the timers (start/reset/pause) and use the variables (current time). Since this interacts with buttons, I thought it'd be better to push that to later. All that said, timers could easily be a module vs part of the core...

An idea would be to check a variable every second in the scheduler and, if it matches, run the scheduled button. That would be very expandable long term with other plugins, such as ProPresenter (when current slide == 7, change the switcher and roll a video, for example). This functionality would be very simple to add, too.

If I'm missing something or if it looks like something won't work, let me know, otherwise I'm going to start working on it.

<img width="709" alt="Screen Shot 2020-07-27 at 1 30 24 PM" src="https://user-images.githubusercontent.com/991168/88578016-7daf1580-d00d-11ea-997d-d5363e3ce9fa.png">

<img width="513" alt="Screen Shot 2020-07-27 at 1 30 36 PM" src="https://user-images.githubusercontent.com/991168/88578026-80aa0600-d00d-11ea-80ed-2a434ab48b11.png">
