### ISSUE TITLE
Feature Request: Button layout rotation on programming page

### ISSUE THREAD

**Issue by BasilChessman** [bitfocus/companion#409]
**Describe the feature**
When rotating buttons on a surface, have the button layout page rotate as well.

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**
no

**Usecases**
Would make programming easier if the button layout rotated to match rotation changes made in surface settings.

**Comment by haakonnessjoen** [comment]
How would you want to do this. As you could have several stream decks connected with different orientations?

**Comment by krocheck** [comment]
I had a couple thoughts on this:
1. In the button tab you can add a rotate button which cycles the layout through the 4 orientations but is simply visual and has no actual configuration implications
2. Add a page option to force an orientation and have the button tab layout follow

**Comment by davidjoshuaford** [comment]
With the excellent updates to the multi-Emulators in version 3 of Companion ahead of us, I can see real value in implementing a vertical mode, particularly for phone usage – holding a phone naturally needs to be vertical, and for one handed operation when walking around a venue. 

There are two things to add here: adding rotation to the emulators, just like the Stream Decks currently have, and

Adding an option to rotate the button building page.

**Comment by Julusian** [comment]
Once we have #1607, perhaps this issue as it stands is no longer necessary?

Instead, it could be that it is possible to define the width & height of an emulator. You could then configure it to be 3x6 or whatever works well for your phone. I almost did this when implementing the emulator styling, but decided to leave it out initially

And perhaps the current way of rotating streamdecks should be deprecated (probably cant be removed for at least a few releases), replacing it with a rotation mode that actually rotates the whole streamdeck, not each button individually. 
Meaning that to rotate a XL, you will need to resize the grid to be at least 8 tall, then once rotated it will take 4x8 of the buttons (rather than the current fixed 8x4)

The combination of these two means that the current orentiation in the UI will always be correct, so we don't have to think about rotating it

**Comment by davidjoshuaford** [comment]
That makes sense for longer term flexibility with multiple devices. Would buttons be renamed into a spreadsheet cell terminology? ie A1, A2..... B1, B2 etc? 

I've been playing around with 4UP stream deck arrays, and also Dashmaster2k windows, and even with four of the new emulators can get a 16x8 grid like this: 
<img width="1680" alt="Screenshot 2022-12-14 at 9 32 29 PM" src="https://user-images.githubusercontent.com/76959770/207887199-7bc3ef7a-c368-451d-99e0-0542e76e046e.png">

If there was a way to name the emulators, and have an action reference that, then four stream deck surfaces could update to act as a single 128 button surface. But maybe this would be unnecessary if the changes you mention about redefining the height and width of the grid take place, or maybe a variable grid design could factor in multiple physical surfaces (ie, create a 16x4 grid that would sit across two XL decks side by side, or 16x8 grid that covers 4 XLs).

**Comment by Julusian** [comment]
This is possible in 3.2 (current beta builds)

A new rotation mode has been added, which allows for the whole streamdeck to be rotated, not just the contents of the buttons. So by using this new mode it will match the layout in the ui
