### ISSUE TITLE
PVP 3: Add support for Layer Presets

### ISSUE THREAD

**Issue by chrisrouse** [bitfocus/companion#460]
This code adds the ability to select from the available Layer Presets. Just needs to be added by someone smarter than me. Moving this request from the module to the main project.

Original request: https://github.com/bitfocus/companion-module-pvp/issues/5

https://gist.github.com/chrisrouse/a14205fa0a1645536b1fa631ca0a415f

**Comment by chrisrouse** [comment]
Updated the gist with better naming and an updated default value to select the first layer by default. This feature is ready to be added.

**Comment by JeffreyDavidsz** [comment]
@chrisrouse check the function please, I'm not quite sure if your value is being send this way. The main send function is sending the cmd variable and {} which is empty. Was editing something, but with no PVP software at hand and a plane to catch, I've just added your function.

**Comment by SteveTherrien** [comment]
Hi @JeffreyDavidsz 

Thanks for spending some time on this, but I have a branch that's almost ready which resolves this issue, #459 and #461. I'm just in the process of testing and documenting it right now. I probably should've posted a note in each of these issues (instead of just #459). Sorry about that.

I'm waiting for PVP's developers to address a bug with effect presets (#462), and I'm trying to gather user input on how effects (#462) and transitions (#463) should best work in Companion (or if they even belong there) before I focus on those.

**Comment by JeffreyDavidsz** [comment]
Ok no problem, was trying to fix some request. Keep up the good work!
