### ISSUE TITLE
Import / Upgrade module 

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#473]
**Describe the feature**
Having a way of importing / upgrading a module into the main application. To quickly add feature to an existing module. 

Also exporting a module files to quickly edit the code. 

**Is this platform dependent (windows, mac, ..)?**
N/A

**If documentation is required to implement, do you know where to find it?**
NA

**Usecases**
Adding an extra feature quickly to test without having to recompile.

**Comment by JeffreyDavidsz** [comment]
I think you are looking for a custom command under each module. But there are reasons for not doing that. Some modules support custom commands because of the variation of actions, bit in most cases we would like to create support for everyone. This is why we want people to let us know if you mis any actions. To quickly add a feature you should set up a developer environment. This way you can add/test your code and start companion from there. You can find information on the wiki page, module development

**Comment by hadphild** [comment]
Agree with Jeff. Just setup the module enviroment.
