### ISSUE TITLE
Vista Lighting Software

### ISSUE THREAD

**Issue by KDLN** [bitfocus/companion#484]
**Describe the feature**
Allow running commands on the Vista (https://www.vistabychromaq.com) software. Choosing different Playlists, and Cue's. 

**Is this platform dependent (windows, mac, ..)?**
Software is on Mac, and PC

**If documentation is required to implement, do you know where to find it?**
https://jands.com/downloads/vistav2/Tbjlt196.pdf

Supports MSC commands.

**Usecases**
Lighting software used in many production environments. House of worship to stadium. Will allow for cleaner show control.

**Comment by Cmillets** [comment]
Here is a link to the facebook thread....there is a pdf on there explaining how to do it. I'm going to be trying it in the next two days but from scrolling through it it looks extremely easy and simple.

https://m.facebook.com/groups/2047850215433318?view=permalink&id=2192333294318342

**Comment by KDLN** [comment]
That software may work for you but on some versions of Mac it does not(mine). I’d also love to remove the amount of programs I have to run in the BG of my production unit.

**Comment by Cmillets** [comment]
> That software may work for you but on some versions of Mac it does not(mine). I’d also love to remove the amount of programs I have to run in the BG of my production unit.

You are right! I just tried it on my mac this morning and the program keep crashing :( I'm on MacOS 10.14

**Comment by josephdadams** [comment]
Until Chroma-Q adds a specific API method to their Vista software, a Vista module in Companion probably won't happen. However, control is possible using OSC to MIDI software and using the Companion Generic OSC module, or using the Companion MIDI Relay module and the corresponding remote software that works with that module. Closing this issue because no API currently exists, and those alternative methods exist.
