### ISSUE TITLE
Add internal actions to change colours

### ISSUE THREAD

**Issue by sphlabs** [bitfocus/companion#495]
**Describe the feature**
Add internal actions, that can be assigned to button presses, to change the text/background colour of any button.

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
One might build a sequence of buttons that need firing in a particular order. As one button is triggered, its colour is changed, and the colour of the next button to press is changed.

A set of buttons that only want to be fired once, but in a random order. As each one is trigged it can change its appearance to indicate it has been fired.

**Comment by krocheck** [comment]
So I have a few questions on how this should handle.

I had a case a couple weeks backs for Watchout where I would have liked to see as tally the last button I pressed and then tally in a different color buttons which are valid presses from that state.  It was a shotbox.

You could implement these as internal under [release] actions, but since they're actions then there's no automated clear ability, as is present within the feedback framework.  So, as-is you'd need to do a 'Clear color' action under the subsequent button to reset the color of the previous button ... and then how do you handle someone pressing the button out of sequence due to error or needing to jump a cue.  Feedback can get way out of whack.

Now, setting a button to internal change its color to show its been fired is much clearer and easy to do.  But, how do we handle the need to reset (beyond relaunching the software).

I'm not quashing this ... just playing devil's advocate based on the structures in place.

**Comment by willosof** [comment]
Hmm. Without having the capacity to go into the concepts of programming with it, it's definitely easy to implement.

**Comment by willosof** [comment]
Done.
