### ISSUE TITLE
Add internal actions to copy/move buttons

### ISSUE THREAD

**Issue by sphlabs** [bitfocus/companion#497]
**Describe the feature**
Internal actions that allow copy/move of an existing button to another location.

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
This could be useful if there is a fixed sequence of buttons that need to be fired, and a limited amount of space (e.g. on a single Stream Deck). The firing of one button could do its job and then replace itself with the next button, copied in from another page.

**Comment by krocheck** [comment]
So issue I see with such an action is that we don't internally handle press-release actions properly ... even for page changes.  e.g. add an action to a button to switch to page 2 and go back to the original page after press ... you'll see the button shows a pressed.  The issue there being the pressed state moved to the button on the new page (and any 'Release Actions' for the button on the new page after release would have run ... rather than the button originally pressed).

Now these are internal core functions that need to be bolstered, but are impediments to getting this sort of change implemented without unintended bugs occurring.

I'm also of the opinion that sort of cue case could be handled with some sort of cue stack ability in the future.  Programming buttons to replace themselves with other buttons seems exceedingly error prone AND inflexible in the face of changes needed to the programming stack under duress.

**Comment by willosof** [comment]
https://dictionary.cambridge.org/dictionary/english/can-of-worms

**Comment by dnmeid** [comment]
I also wouldn't recommend self replacing buttons for mimicking sequence behavior. But I've used move macros on gMA sometimes. This can be helpful to build conditionals. You can e.g. have a bank swap to different banks and now trigger one of them with a fourth bank.
I also used it for temporary disabling external control. Lets say some external device triggers bank 50.1 and sometimes this is empty and sometimes not.

**Comment by Julusian** [comment]
A better solution for the original usecase is #1630 
I strongly believe that it shouldnt be possible for buttons to self-modify like this, its going to introduce all kinds of weird behaviour and accidental data deletion for users(both their fault and ours)
