### ISSUE TITLE
TCP Client ( Telnet )

### ISSUE THREAD

**Issue by jsuofga** [bitfocus/companion#524]
**Describe the feature**
A generic Telnet client module . 
There are many older equipment that require TELNET to communicate with.
For example the Cisco Network switches still require TELNET and does not have a HTTP API

The User Input fields would be:
1. IP Address
2. PORT Number
THen allow user to send string to the device via telnet

**Is this platform dependent (windows, mac, ..)?**
Explain

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by haakonnessjoen** [comment]
You should rather explain what equipment you want to control. If you want to control a cisco, tell us which functionality you want to control. We are not dependant upon a http api to make modules for new software or equipment. We have at least 3 modules that uses telnet.

We cannot make a generic telnet or tcp socket module yet, because that would stop a lot of people from sending us requests about new modules, or even stop them from making modules themselves. We try to make this software easy for everyone. Not just "hard core users" that know protocols :)
