### ISSUE TITLE
BMD ATEM User suggestion

### ISSUE THREAD

**Issue by doaremeng** [bitfocus/companion#533]
I am a BlackMagic ATEM user, using your software instead of keyboard operation, great! However, there are 3 buttons (Pageup/Pagedown/Pageno) that are always occupied. Is there an option to close 3 page flip buttons, and let 15 buttons be customized?

There is also a solution where 3 page flip buttons can be moved.

Or page turning can be specified as a button press or a combination of a button plus a button

**Comment by haakonnessjoen** [comment]
This is already covered by issue #66

Just a side note; next time you open a ticket, try to make a more fitting title, like in this case, it would be "Request: Support for removing page buttons"

Or if you are unsure if a feature is there, but you just have not found it, try the facebook page or slack first :)

**Comment by Paradox32** [comment]
bump.. I'll 2nd this feature request.. I don't really need to know what page I'm on, so if I could remove the page indicator button and utilize it for something else that would be fantastic.. I also didn't see a way to move the page buttons maybe to a different button instead of on the left side only.
