### ISSUE TITLE
Module request: Characterwoks HTTP POST control

### ISSUE THREAD

**Issue by xavifumi** [bitfocus/companion#535]
Hi, we are using Characterworks for all our CG work on our live chanel and it is really easy to use it throug it's HTTPS POST remote control:

https://www.chrworks.com/help/

We are starting to use Companion on our pipeline, but can't control the CG with the available options...

Can we help to provide the module? Thanks in advance!
Xavi

**Comment by xavifumi** [comment]
I mainly use the instructions you are working on. Maybe I miss the "set_text" command for changing lower thirds.
Thanks a lot! When can we test it? :) 
Thanks a lot!!

**Comment by ewettach** [comment]
I have added the set_text function as you requested.  Currently I am waiting to hear back from devs in order to get an "official" repository for it, but for your testing, you can access it at the link below.

[https://github.com/ewettach/companion-module-characterworks](url)

I recommend looking at the HELP.md file for instructions

**Comment by JeffreyDavidsz** [comment]
Sorry guys it took long to create a repo. Did you ask it on slack also? I've created one for you, you should have mail.
