### ISSUE TITLE
slows down/halts over time

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#608]
Companion (latest builds) seems to slow down over time in some cases.
We don't know more than that yet, but we'd love to hear our users take on it.

How can you reproduce it?
Which instances are you using when it's happening?
OS? 
Build?

**Comment by richardgatarski** [comment]
I've been running 8f4539c for 24 hours with vMix and XR module, no problems with slowing down. Win 10, and Edge.

**Comment by chrisrouse** [comment]
Noticed this today. Mac running 10.13 with Companion running in Safari.

Things I saw along with it:

- Moving the mouse started to lag. 

- I can't click in the middle of a button text label and fix a typo. I have to remove the entire label to fix it. If you try to type in the middle it just puts the letter at the end. Using the arrow key just gets you into a fight with the cursor.

- I moved to the latest bleeding edge and still saw the second issue, but the first seemed to be better, but I didn't have it running for as long before we finished for the day. 

We're building across four Stream Decks setting up for the NFL Draft. I have 5 pages full of buttons so far. The first 32 buttons are formatted as ARI\nCardinals, and have a background color. Some also have a different text color to make it easier to read. The font is set to 14pts on each button. I copied the same button across all 12 buttons on each page. Right now every cue just selects a playlist in PVP, but I'll be adding an internal page cue to every button tomorrow.

**Comment by willosof** [comment]
How did it turn out @chrisrouse ? Did it happen multiple times? You're running latest build or 1.3.0?

**Comment by henkstom** [comment]
I have a Bitfocus install:
- no Connections / Instances
V1.3.0 (fd1f928-1497)

after a while the response is very slow 

the machine has been in sleep state
I can reproduce this

20. 16:40:12 CORE(cb): db.tmp->db failed: Error: ENOENT: no such file or directory, rename '/Users/henkstomphorst/Library/Application Support/companion//db.tmp' -> '/Users/henkstomphorst/Library/Application Support/companion//db'
20. 16:35:55 system(power): Suspending

**Comment by willosof** [comment]
Hi @henkstom, how would you reproduce this, and how is this related (in the process) to the sleep state?

**Comment by SteveTherrien** [comment]
I had the same problem on April 26:
- changing a button's text is delayed (you type and there's a delay before the text on the Stream Deck updates)
- when it gets really bad, the textbox in Companion fights me like how @chrisrouse described

I was able to get back there yesterday and could duplicate the problem twice using the same build (`1.3.0 f6629e5-1455`):

1. The first time, I let it run for 2-3 hours and saw the delayed button text, and eventually just the `db.tmp->db failed: Error: ENOENT...` error @henkstom described. Restarting Companion cleared the problem.
2. I then switched to the newest build (`1.3.0 05c27f2-1513`) using the same config and let it run for about an hour. No slowdowns.
3. I switched back to the older build, let it run for about an hour, and saw the button text slowdown problem.
4. Switched back to the newest build, let it run for about an hour, no slowdowns.

Companion wasn't being used during this time, aside from the occasional button press to see how it responded.

Both on April 26 and my first test yesterday, I had the Web Buttons page open on an external device. I didn't have it open for tests 2-4.

This was running on macOS High Sierra 10.13.6 with only a single Stream Deck connected. The system did not go into any power saving mode.

I may be able to run some more tests this Friday if there's anything you'd like me to try.

**Comment by JeffreyDavidsz** [comment]
@SteveTherrien so what you are saying is a later build is fine, but somewhere between 1.3.0 stable and the latest you used is an error?

**Comment by SteveTherrien** [comment]
@JeffreyDavidsz the later builds didn't seem to glitch out after an hour for me, but I wouldn't give it the green light without a more thorough test. I'll try to get in there on Tuesday or Friday and let it run for most of the day.

**Comment by SteveTherrien** [comment]
@JeffreyDavidsz, I was able to do more testing there today. The problem still exists in the latest build though I figured out what's happening and how to replicate it.

1. Run Companion (`npm run start` and keep the console open). Edit the text of a button. The edit is instant. The console shows the image was invalidated.
2. Open the tablet or emulator view in a lot of tabs (20+).
3. Edit the button's text again. It's now slowed down because it needs to update the button on all those tabs.
4. Close all those extra tabs and change the button's text. It's still slow.

The console shows that even though those web socket connections are closed, Companion is still trying to invalidate that image for those phantom connections.

Using the arrows keys in a button's label triggers Companion to save its DB and invalidate the image for all those connections. This is why @chrisrouse and I both saw the button's label fighting us when we tried to use the arrow keys.

I think there's also a race condition when a save process takes a long time to complete if it has a lot of images to invalidate. The console shows `db_save begin`, dozens of `Invalidated image ... bank-update saving`, and a final `db_save written/renamed` after it has finished invalidating. This is likely the cause of the `Error: ENOENT: no such file or directory, rename 'db.tmp' -> 'db'` message @henkstom and I also saw.

But no one opens dozens of tabs. So how can this get triggered?
1. Start Companion
2. Launch the GUI. Refresh the page a dozen times.
3. Change a button's text. You'll still see a dozen `Invalidated image` messages.

A long-running Companion process that sees people come and go will eventually run into this problem.

How else? If you're using Companion on a mobile device (like the tablet or emulator page) and the device goes to sleep or suspends the browser tab, when that tabs wakes up a new connection will get made, and another phantom connection will need to be invalidated.

**Comment by willosof** [comment]
It's so weird I never experience this..

**Comment by SteveTherrien** [comment]
I either have a computer or an environment that's prone to this happening within a few hours of use, but I'm having a lot of trouble narrowing down the source. What I described [above](https://github.com/bitfocus/companion/issues/608#issuecomment-496736054) is accurate but I don't think it's the only cause.

I'm starting to suspect [PJLink module makes companion slower after a while](https://github.com/bitfocus/companion-module-pjlink/issues/2). A while back I disabled all modules except the location's four projectors and I still had the slowdown.

It's one of those problems that only happens when I don't have the time to investigate into it.

**Comment by monoxane** [comment]
I've been running 1.3 with some modifications for a few months now, when I use companion via rosstalk its fine but when I use the web buttons or a stream deck it can take up to 10 second for an action to happen when its been running for a couple of weeks

**Comment by haakonnessjoen** [comment]
I will have to do some research in regards of zombie-websock-connections. A bit weird, but I have seen some weird messages in the log in regards of the preview listener, so there might be something to it. PJLink has also been mentioned a few times in relation to slowness. So if anyone could, please do some testing with/without pjlink also.

**Comment by monoxane** [comment]
Relevant #795

**Comment by Julusian** [comment]
It sounds like this has gone away with time.
If anyone is still having a problem with this, please try to narrow down which module(s) need to be enabled for it to happen and open a new issue
