### ISSUE TITLE
[Request] Exit and start Streamdeck.exe

### ISSUE THREAD

**Issue by lightman88** [bitfocus/companion#758]
I have a bat file written for opening Companion and closing the streamdeck software with:

@echo off
SETCONSOLE /hide
taskkill /f /im StreamDeck.exe
timeout 2
START C:\"Program Files"\Companion\Companion.exe

I was wondering if there was a way to do the reverse, close companion and open Streamdeck as sort of a quick software hot-swap

**Comment by willosof** [comment]
Force killing companion like you do might lead to a corrupt database file, or unsaved changes if you're unlucky.

**Comment by DeeJayMX** [comment]
I need to restart the app from automation like a script, is there a way to go it gently from outside the app like a commandline on the companion.exe image ?

**Comment by willosof** [comment]
As of 10 seconds ago, you can now kill companion via an internal action :)

**Comment by DeeJayMX** [comment]
Great !
But where or How ?

**Comment by josephdadams** [comment]
@DeeJayMX make sure you are using one of the latest builds, available from [builds.bitfocus.io](http://builds.bitfocus.io). Closing this since you can now both kill Companion and restart Companion as internal actions. You can accomplish what you want (close Companion and open Elgato software) by putting the kill Companion action on a button and activating that button via CURL in your script.
