### ISSUE TITLE
Generic XML Module

### ISSUE THREAD

**Issue by AZJAYNES** [bitfocus/companion#784]
**Describe the feature**
Is there a way to make a module that we could use to fire or test strings to a specific ip as TCP, UDP, HTTP on a specified port so we could test control without having to involve additional software?

**Is this platform dependent (windows, mac, ..)?**
Mac and PC 

**Usecases**
i was looking to loop a single clip on a Blackmagic Design Hyperdeck Studio Mini and i had the manual and a pile of commands to try and monkey punch my way through finding the code combinations that achieved the desired result,  I eventually found the external device control in the Barco Event Master software but it would be helpful to test with fewer software in line.  

![IMG_1522](https://user-images.githubusercontent.com/51722071/62838996-bb6a3100-bc38-11e9-9541-1aac751221ac.png)

**Comment by josephdadams** [comment]
Closing this request because we prefer to make device/protocol specific modules with concrete actions. This is the best for end-users. If there are things you are testing against your devices that would be nice to have added to that specific Companion module, please submit an issue to that specific repository and/or submit a pull request for it.
