### ISSUE TITLE
While I realise that V2 is not for use in a production environment, I am using it just with the  32 key stream deck, Qlab, and S3 Barco. So far so good. Are the parts that have to do with V2 not being stable including those three products? I'd really like to use Companion for this application.

### ISSUE THREAD

**Issue by PGatesGallus** [bitfocus/companion#786]
**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by haakonnessjoen** [comment]
It is not stable because it is still in development, and big bugs could occur. It does not necessarily mean that it is buggy. But at any point, somone could upload a change to 2.0 that breaks everything. Or a particular tiny thing. And who know if you download a version that has a giant bug in it, or not :)

So, you can run development release if you want. But it is even more your own fault if anything would go wrong in production.

One known issue, is that you should not use the Stream Deck application that comes from elgato, with companion 2.0 (daily build), since the plugin for stream deck is not updated yet.
