### ISSUE TITLE
StreamDeck XL - Button Locations

### ISSUE THREAD

**Issue by WNTLtd** [bitfocus/companion#803]
**Describe the bug**
The placement of Companion buttons on the StreamDeck XLs' Action Instance Area (Canvas) is not correct.
It's still representing the first 15 keys of a StreamDeck (NON XL) layout and just extending the numbering right with an extra forth line on the bottom.
It **IS CORRECT** however in the browser when laying out the keys for programming their actions in Companion.
i.e.
1.1   - 1.2   - 1.3  - 1.4   - 1.5    - 1.6  - 1.7    - 1.8
1.6  - 1.7   - 1.8  - 1.9   - 1.10  - 1.11  - 1.12  - 1.13
1.11 - 1.12 - 1.13 - 1.14 - 1.15  - 1.16 - 1.17  - 1.18
1.16 - 1.17 - 1.18 - 1.19 - 1.20 - 1.21 - 1.22 - 1.23

**Expected behavior**
Whereas (obviously) they should be laid out:
1.1    - 1.2   - 1.3   - 1.4    - 1.5   - 1.6   - 1.7   - 1.8
1.9   - 1.10  - 1.11  - 1.12  - 1.13 - 1.14 - 1.15  - 1.16
1.17  - 1.18 - 1.19  - 1.20 - 1.21 - 1.22 - 1.23 - 1.24
1.25 - 1.26 - 1.27 - 1.28 - 1.29 - 1.30 - 1.31 - 1.32

**Screenshots**
Screen shot(s) attached.
![Screenshot 2019-09-01 at 11 45 14](https://user-images.githubusercontent.com/52933483/64075285-39f14600-ccae-11e9-961f-f45a71f86d37.png)
![Screenshot 2019-09-01 at 11 44 45](https://user-images.githubusercontent.com/52933483/64075287-3d84cd00-ccae-11e9-8643-dde9d0f24bbb.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome
 - Version : Companion v2.0.0 (fee6ef2), SD v4.3.2 (11299)

**Comment by haakonnessjoen** [comment]
![image](https://user-images.githubusercontent.com/416667/64078411-98ccb480-ccda-11e9-8890-b5e66ed2fcf4.png)

If you look at the known issues when you start companion, it mentions the plugin support as not finished. #688 which is what you are experiencing here.

If you use XL natively from companion instead of using the stream deck application, you will not have this issue.

**Comment by trekfan42** [comment]
My workaround so far is to make a streamdeck folder and put companion buttons inside it and change the default companion layout like so:

[ SD back ] [ 1.1 ] [ 1.2 ] [ 1.3 / 1.4 / 1.5 / 1.6 / 1.7 / 1.8 /

then leave the first 3 buttons blank in the next 3 rows.
this actually isn't too bad because it gives me 9 regular streamdeck buttons..

here is my full page export for companion button pages 
[LAPTOP-VNP84637_full-config_20190920-1356.txt](https://github.com/bitfocus/companion/files/3637151/LAPTOP-VNP84637_full-config_20190920-1356.txt)

just rename .txt to .companionconfig

**Comment by nikb72** [comment]
Wondering why this bug is closed, I've just installed 4.8.1.13027 Streamdeck with an XL pad & running Companion 2.0.0-b9a2e33-2446 and I'm having exactly the same issues. 
Is there anyway to change the mapping manually?

**Comment by josephdadams** [comment]
Are you using the stream deck software at the same time as Companion?

**Comment by haakonnessjoen** [comment]
Hi,

This is a known problem if you are using Companion 2.0 with the elgato plugin for 1.4.

If you insist on using the Stream Deck Application together with Companion, you need to download the 2.0 beta plugin for the stream deck application:

https://s3.bitfocus.io/builds/plugin/io.bitfocus.companion-plugin.streamDeckPlugin
