### ISSUE TITLE
PAGE Buttons skip/double tap

### ISSUE THREAD

**Issue by ScottGlascock** [bitfocus/companion#879]
**Describe the bug**
Pressing the PAGE UP or PAGE DOWN buttons skips a page. (Seems to act like a double press)
If on PAGE 1 and press UP, will go to PAGE 3 (then 5, then 7, etc). Press DOWN will go to PAGE 98, (then 96, 94, etc).

Looking in the LOG, every time you press an UP or DOWN page button, you get two lines of feedback. Perhaps it is registering a command on both the key down and the key up.

**Expected behavior**
I expect the page to only increase or decrease by 1 each time, not 2.

**Comment by haakonnessjoen** [comment]
Sounds like you are experiencing side-effects of using the stream deck plugin inside the stream deck application as well as companion. Either exit the stream deck application, and let companion control the stream deck alone, or physically reconnect your stream deck device after starting companion. This should leave you with only the app controlling the device at once.

**Comment by dnmeid** [comment]
I have this too, not with the emulator but with the real stream deck.

**Comment by dnmeid** [comment]
Should be fixed now in 6314436c18acd9d251f5b43c4841f2838efb89b6
Originally the page_up page_down events had invoked a inc_page or dec_page event depending on the flip direction userconfig. It seems that the event triggers an additional pagechange somewhere else. I now put the code in functions instead of event listeners an call the functions with the events, so no double trigger.
Companion code seems to get more and more messy.
