### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by jeffmikels** [bitfocus/companion#932]
There are a number of ways to access Companion functions over the network:

* There are TCP / UDP functions
* Some functions are available over REST
* Some functions are available over socket.io
* Some functions are available over OSC

However, there is no documentation for these, and as a result, there is also no consistency between them. I want to help, but I need help finding the available functions in the code.

Point me in the right direction, and I'll do some documenting.

**Comment by josephdadams** [comment]
@jeffmikels look at /lib/server_tcp.js, server_udp.js etc. They emit events up to server_api.js. server_http.js emits also

**Comment by krocheck** [comment]
The new UI exposes documentation for the remote control protocols under the "Settings" tab.  I'm going to close this but feel free to re-open if you think there's more work to be done here.

**Comment by pyahmed** [comment]
Is there any documention (on the protocol) how to receive "system-wide" updates via socket.io similar to the tablet / emulator pages?

**Comment by Julusian** [comment]
This is an old issue, talking about different protocols and documentation that was solved. A new issue or discussion would have been a better place for this.

But no there isn't any documentation because the socket.io protocol is an internal api that breaks at random based on the needs of the ui. As such we don't recommend using it for other applications, and so there is no documentation.
If you really want to use it despite the warnings, you will have to read the code to figure out. There is now a convient place which describes all of the possible messages https://github.com/bitfocus/companion/blob/main/shared-lib/lib/SocketIO.ts, but still be aware that there will be small changes to existing messages with each new release of companion
