### ISSUE TITLE
Windows 10 32bit build

### ISSUE THREAD

**Issue by Opgenorth** [bitfocus/companion#935]
I have a touchscreen tablet running Windows 10 32bit OS that I'd like to use Companion  V2.0 with, but it appears there're only 64bit Windows builds.  Is it possible to add 32bit builds?

**Comment by josephdadams** [comment]
I think you can set up your own development environment and build a 32-bit version yourself. Correct me if I'm wrong, @haakonnessjoen?

**Comment by Julusian** [comment]
Quite a few of the native dependencies we use do not provide prebuilds for 32bit windows, and seeing as demand for this seems low, I dont think this is worth us doing.
Instead of running companion directly on the tablet, you could instead run it on a raspberry pi 4, and still control it from the tablet.

Additionally, windows 11 does not have a 32bit version (and 32bit support on other platforms is incredibly limited), so I expect us supporting a 32 bit build will only get harder over time
