### ISSUE TITLE
Universal feature request for Increment and Decrement button actions

### ISSUE THREAD

**Issue by gathomasjr** [bitfocus/companion#954]
**Describe the feature**
There are Companion Key Down/On Actions for 'Internal: Button press and release' and 'Internal: Increment page number' and '...Decrement page number'.
Is it possible to add actions for 'Internal: Increment button number then press and release' and 'Internal: Decrement button number then press and release' on a specified page, based on what was last pressed on that particular page? If so, these actions could solve a world of unique situations.

I want to use it to step through ATEM Media Player stills. However this feature could perform lots of other stuff, like setting up a group of commands on a page and then stepping through and executing each in order from multiple presses of one button .

The Key Down/On Action options would require these user supplied items.
1. A page number for the operation.
2. A choice of Increment or Decrement.

The last button pressed on each page should be stored in an array.
The array should be updated each time a button is pressed.
If a button has not been pressed on a page yet, that page's last button press should default to position 1.

When the user presses a button containing an Increment or Decrement button Action, Companion should retrieve the page number option of the pressed button. Companion then retrieves the last button number pressed on that page from the array and adds +1 or -1 to it. This calculated button number (on the page number retrieved above) then receives a press and release action .

I love Companion. Thanks for a great package.
George Thomas

**Is this platform dependent (windows, mac, ..)?**
I believe all platforms and supported devices could benefit from this feature.

**If documentation is required to implement, do you know where to find it?**
I believe this is all internal to Companion.

**Usecases**
I could really use next/previous for the ATM Media Players too. The ATEM Switcher Control software cannot make a macro that will do this. BlackMagic's macros only allow you to select a specific media player still, not increment or decrement through them. Having the ability for Companion to increment or decrement through button presses on a page would allow this.
I see there are Companion Presets for ATEM Mediaplayers. While they allow us to directly select from the 20 stills in a switcher, it doesn't really allow us to increment or decrement through them. The feature requested above would allow me to set up a page with 20 buttons for the 20 stills in Mediaplayer and step through them in order from a single increment and single decrement button on my main page for the switcher.

I am certain there are other cases that could take advantage of this.  Like stacking commands on a page and stepping through them one at a time in order.

**Comment by Julusian** [comment]
I'm not 100% sure that I follow what you are asking for, but I think I understand enough.

My first thought is that this is a reasonable size feature and I believe it is too late for new stuff like this to be done for 2.0, but it could be done for the next version after that. Adding an increment/decrement to the ATEM module will definitely be possible for 2.0.

I think this will be solvable with some of the functionality planned for 3.0, I don't think the plans are written anywhere but I remember this from the slack channel a while ago. The idea is that instead of pages there will be a large workspace, and each streamdeck will have multiple windows into this area. 
So you could achieve the same behaviour by putting the increment button as its own window, and then each button pressed will perform an action, inlcuding moving that window in the workarea.

**Comment by gathomasjr** [comment]
Thanks for the reply Julian.

Essentially what I need are Key Down/On Action options for ATEM Mediaplayer Increment Still and Decrement Still buttons. This can’t be done with ATEM macros because Blackmagic only allows you to specify Mediaplayer source 1 – 20 directly.

The suggestion about making a Universal feature was only a thought. And it doesn’t seem practical if pages are going away anyway.

Just the ability to step through ATEM Mediaplayer stills would work great for my use.

Thanks again for the great application this team developed!
George

**Comment by scotth1** [comment]
This sounds like a feature I've been thinking about, correct me if I'm wrong. But I want to do a similar thing in the H2R Graphics, my thought was to use a variable that is expanded in the index value ${h2r-lowerthird-var}  and have an internal action "increment variable" and "decrement variable" and modules can already support dynamic variables. So that requires modules to make the dynamic variable visible for all possible variables that might potentially be used which isn't as generalised as being able to just create a variable at a global level and have it expanded in a value field.

**Comment by WoozleEffect** [comment]
This is pretty much exactly what I am looking for.
Being able to toggle a timer's hours, minutes, or seconds, up or down by increments of 1.
Or, for ATEM, increment the selected hyper deck clip. I could then use a trigger to detect the change and post that number... possibly.

Honestly, I'm really close to losing hope on a few things. If I could use a companion variable within a JSONPath, or concatenate one variable into another, and use THAT as a JSONPath.... And as someone who really doesn't know how to code, I'm just figuring this all out by rote and trial and error.... lots and lots of error.

**Comment by Julusian** [comment]
Reading through all of this, I am pretty sure that all of these cases can be solved today with custom-variables and expressions.
Not a perfect match to what is being asked for, but I think it can replicate it all.
